src/.editorconfig, src/Playwright.Chromium/Playwright.Chromium.csproj, src/Playwright.Firefox/Playwright.Firefox.csproj, src/Playwright.Webkit/Playwright.Webkit.csproj, src/PlaywrightSharp.Abstractions/PlaywrightSharp.Abstractions.csproj, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp.Tests/XmlCommentTestExample.cs, src/PlaywrightSharp.sln, src/PlaywrightSharp/Playwright.cs, src/PlaywrightSharp/PlaywrightSharp.csproj
=> First scaffolding

src/PlaywrightSharp.Abstractions/Dialog.cs, src/PlaywrightSharp.Abstractions/DialogEventArgs.cs, src/PlaywrightSharp.Abstractions/DialogType.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.TestServer/PlaywrightSharp.TestServer.csproj, src/PlaywrightSharp.Tests/BrowserContext/BrowserContextTests.cs, src/PlaywrightSharp.Tests/Page/Events/DialogTests.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj
=> Dialog tests

.github/workflows/main.yml, .github/workflows/no-puppeteer.sh, src/PlaywrightSharp.Abstractions/Accessibility/AccessibilitySnapshotOptions.cs, src/PlaywrightSharp.Abstractions/Accessibility/CheckedState.cs, src/PlaywrightSharp.Abstractions/Accessibility/IAccessibility.cs, src/PlaywrightSharp.Abstractions/Accessibility/SerializedAXNode.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Tests/Accessibility/AccessibilityTests.cs, src/PlaywrightSharp.Tests/Accessibility/PlainTextContentEditableTests.cs, src/PlaywrightSharp.Tests/Accessibility/RootOptionTests.cs, src/PlaywrightSharp.Tests/Attributes/SkipBrowserAndPlayformFact.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserBaseTest.cs, src/PlaywrightSharp.Tests/BrowserContext/BrowserContextTests.cs, src/PlaywrightSharp.Tests/BrowserContext/BypassCSPTests.cs, src/PlaywrightSharp.Tests/BrowserContext/JavaScriptEnabledTests.cs, src/PlaywrightSharp.Tests/BrowserContext/SetUserAgentTests.cs, src/PlaywrightSharp.Tests/Page/Events/DialogTests.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp.Tests/TestConstants.cs, src/PlaywrightSharp.sln, src/PlaywrightSharp/PlaywrightSharp.csproj
=> Accessibility tests

src/PlaywrightSharp.Abstractions/AddTagOptions.cs, src/PlaywrightSharp.Abstractions/BrowserContextOptions.cs, src/PlaywrightSharp.Abstractions/ColorScheme.cs, src/PlaywrightSharp.Abstractions/EmulateMedia.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Abstractions/MediaType.cs, src/PlaywrightSharp.Abstractions/PageEvent.cs, src/PlaywrightSharp.Abstractions/WaitForEventOptions.cs, src/PlaywrightSharp.Tests/BrowserContext/TimezoneTests.cs, src/PlaywrightSharp.Tests/Page/EmulateMediaColorSchemeTests.cs, src/PlaywrightSharp.Tests/Page/EmulateMediaTypeTests.cs, src/PlaywrightSharp.Tests/Page/EmulateTests.cs, src/PlaywrightSharp.Tests/Page/ViewportTests.cs, src/PlaywrightSharp.Tests/TestConstants.cs
=> emulate tests

src/PlaywrightSharp.Abstractions/BrowserContextOptions.cs, src/PlaywrightSharp.Abstractions/GotoOptions.cs, src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Abstractions/IResponse.cs, src/PlaywrightSharp.Abstractions/NavigationOptions.cs, src/PlaywrightSharp.Tests/BrowserContext/IgnoreHttpsErrorsTests.cs
=> ignore HTTPS errors tests

.github/workflows/chromium.yml, .github/workflows/code-style.yml
=> Add chromium actions

src/PlaywrightShap.Firefox/PlaywrightSharp.Firefox.csproj, src/PlaywrightShap.Webkit/PlaywrightSharp.Webkit.csproj, src/PlaywrightSharp.Chromium/ChromiumBrowserType.cs, src/PlaywrightSharp.Chromium/PlaywrightSharp.Chromium.csproj, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserBaseTest.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp.Tests/TestConstants.cs
=> Launch browser scafolding

src/PlaywrightSharp.Tests/Page/ClickTests.cs, src/PlaywrightSharp/BrowserFetcher.cs
=> complete v0.10.0 click spec

src/PlaywrightSharp.Tests/Page/WaitForLoadStateTests.cs
=> update navigation.spec.js to v0.10.0

src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/IFrameExecutionContext.cs, src/PlaywrightSharp.Tests/Evaluation/FrameEvaluateTests.cs
=> take evaluation tests to v0.10.0

src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/BrowserFetcher.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Request.cs, src/PlaywrightSharp/Transport/SlowMoTransport.cs
instead of something like
```cs
/// <inheritdoc cref="IBrowserContext"/>
public Task CloseAsync() ...
```
it should be
```cs
/// <inheritdoc cref="IBrowserContext.CloseAsync"/>
public Task CloseAsync() ...
```
=> fixed docs references

src/PlaywrightSharp.Tests/Browser/CloseTests.cs, src/PlaywrightSharp.Tests/Browser/DisconnectTests.cs, src/PlaywrightSharp.Tests/Browser/IsConnectedTests.cs, src/PlaywrightSharp.Tests/Chromium/Browser/TargetEventsTests.cs, src/PlaywrightSharp.Tests/Chromium/Launcher/BrowserUrlOptionTests.cs, src/PlaywrightSharp.Tests/Chromium/Launcher/WebSocketOptionsTests.cs, src/PlaywrightSharp.Tests/Launcher/ConnectTests.cs, src/PlaywrightSharp.Tests/Launcher/DefaultArgumentsTests.cs, src/PlaywrightSharp.Tests/Launcher/HeadfulTests.cs, src/PlaywrightSharp.Tests/Launcher/LaunchTests.cs, src/PlaywrightSharp.Tests/Launcher/LaunchWebSocketOptionTests.cs, src/PlaywrightSharp.Tests/Launcher/UserDataDirTests.cs, src/PlaywrightSharp.Tests/TestConstants.cs
=> Add headful tests

src/PlaywrightSharp.Abstractions/IBrowserContext.cs, src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserApp.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserType.cs, src/PlaywrightSharp.Chromium/ChromiumConnection.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumSession.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Chromium/Protocol/Protocol.Generated.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserBaseTest.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserContextBaseTest.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpPageBaseTest.cs, src/PlaywrightSharp.Tests/Page/PageUrlTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/IBrowserContextDelegate.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> chromium page.url tests

src/PlaywrightSharp.Tests/Launcher/LaunchWebSocketOptionTests.cs, src/PlaywrightSharp/BrowserApp.cs
=> Chromium: Pass LauncherTests.LaunchWebSocketOptionTests tests

src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Chromium/ChromiumSession.cs, src/PlaywrightSharp.Tests/Launcher/LaunchTests.cs, src/PlaywrightSharp/Frame.cs
=> Pass launch tests

src/PlaywrightSharp.Abstractions/Clip.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Abstractions/PlaywrightSharp.Abstractions.csproj, src/PlaywrightSharp.Abstractions/ScreenshotOptions.cs, src/PlaywrightSharp.Abstractions/ScreenshotType.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleScreenshotTests.cs, src/PlaywrightSharp.Tests/Page/ScreenshotTests.cs, src/PlaywrightSharp/Page.cs
=> Screenshot tests

src/PlaywrightSharp.Tests.DumpIO/PlaywrightSharp.Tests.DumpIO.csproj, src/PlaywrightSharp.Tests.DumpIO/Program.cs, src/PlaywrightSharp.Tests/Launcher/FixturesTests.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp.sln
=> Fixture tests

src/PlaywrightSharp.Abstractions/ITarget.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Tests/Chromium/HeadfulTests.cs
=> Chromium headful tests

src/PlaywrightSharp.Abstractions/IBrowser.cs, src/PlaywrightSharp.Abstractions/ICoverage.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Chromium/ChromiumSession.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBaseTest.cs, src/PlaywrightSharp.Tests/Chromium/SessionTests.cs, src/PlaywrightSharp/Page.cs
=> Add chromium session tests

src/PlaywrightSharp.Abstractions/IBrowser.cs, src/PlaywrightSharp.Abstractions/TracingOptions.cs, src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Tests/Chromium/TracingTests.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj
=> Add tracing tests

src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserBaseTest.cs, src/PlaywrightSharp.Tests/Chromium/OopifTests.cs
=> Chromium: Add OOPIF tests

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserBaseTest.cs, src/PlaywrightSharp.Tests/Chromium/PdfTests.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Add PDF tests

src/PlaywrightSharp.Abstractions/IBrowserContext.cs, src/PlaywrightSharp.Tests/BrowserContext/PermissionsTests.cs, src/PlaywrightSharp/BrowserContext.cs
=> Add permissions tests

src/PlaywrightSharp.TestServer/SimpleServer.cs, src/PlaywrightSharp.Tests/Webkit/ProvisionalTests.cs
=> Webkit: Provisional tests

src/PlaywrightSharp.Tests/BrowserContext/JavaScriptEnabledTests.cs
=> Chromium: Pass JavascriptEnabledTests

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserType.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Firefox/FirefoxBrowserType.cs, src/PlaywrightSharp.Tests/BrowserContext/SetUserAgentTests.cs, src/PlaywrightSharp.Tests/TestConstants.cs, src/PlaywrightSharp/DeviceDescriptors.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass SetUserAgentTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleBoundingBoxTestsTests.cs
=> Chromium: Pass ElementHandleBoundingBoxTests tests

src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleClickTests.cs, src/PlaywrightSharp/ElementHandle.cs
=> Chromium: Pass ElementHandleClickTests

src/PlaywrightSharp.Chromium/ChromiumExecutionContext.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Firefox/FirefoxExecutionContext.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Evaluation/FrameEvaluateTests.cs, src/PlaywrightSharp.Tests/Evaluation/PageEvaluateOnNewDocumentTests.cs, src/PlaywrightSharp.Tests/Evaluation/PageEvaluateTests.cs, src/PlaywrightSharp/ExecutionContext.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/FrameExecutionContext.cs, src/PlaywrightSharp/Helpers/JsonHelper.cs, src/PlaywrightSharp/Helpers/StringExtensions.cs, src/PlaywrightSharp/IExecutionContextDelegate.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/JSHandle.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass Evaluation tests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleContentFrameTests.cs
=> Chromium: Pass ElementHandleContentFrameTests

src/PlaywrightSharp.Abstractions/ClickOptions.cs, src/PlaywrightSharp.Abstractions/IElementHandle.cs, src/PlaywrightSharp.Abstractions/IPointerActionOptions.cs, src/PlaywrightSharp.Abstractions/Input/Modifier.cs, src/PlaywrightSharp.Abstractions/PointerActionOptions.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleHoverTests.cs, src/PlaywrightSharp/ElementHandle.cs
=> Chromium: Pass ElementHandleHoverTests

src/PlaywrightSharp.Abstractions/IBrowserContext.cs, src/PlaywrightSharp.Abstractions/IElementHandle.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Chromium/ChromiumExecutionContext.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Firefox/FirefoxBrowserContext.cs, src/PlaywrightSharp.Firefox/FirefoxExecutionContext.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleOwnerFrameTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Helpers/ArrayExtensions.cs, src/PlaywrightSharp/Helpers/StringExtensions.cs, src/PlaywrightSharp/Helpers/TempDirectory.cs, src/PlaywrightSharp/IBrowserContextDelegate.cs, src/PlaywrightSharp/IPageDelegate.cs
=> Chromium: Pass ElementHandleBoundingBoxTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleScrollIntoViewIfNeededTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleVisibleRatioTests.cs, src/PlaywrightSharp.Tests/Page/ClickTests.cs, src/PlaywrightSharp/ElementHandle.cs
=> Chromium: Pass ElementHandle VisibleRatioTests ScrollIfNeeded

src/PlaywrightSharp.Tests/Frame/FrameEvaluateHandleTests.cs
=> Chromium: Pass FrameEvaluateHandleTests

src/PlaywrightSharp.Chromium/Input/ChromiumRawKeyboard.cs, src/PlaywrightSharp.Firefox/Input/FirefoxRawKeyboard.cs, src/PlaywrightSharp.Tests/Page/ClickTests.cs, src/PlaywrightSharp/Input/IRawKeyboard.cs, src/PlaywrightSharp/Input/Keyboard.cs
=> Chromium: Pass click tests

src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleAsElementTests.cs
=> Chromium: Pass JSHandleAsElementTests

src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleJsonValueTests.cs
=> Chromium: Pass JSHandleJsonValueTests

src/PlaywrightSharp.Chromium/ChromiumExecutionContext.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleToStringTests.cs, src/PlaywrightSharp/JSHandle.cs
=> Chromium: Pass JSHandleToStringTests

src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Tests/Page/PageWaitForTests.cs, src/PlaywrightSharp/Dom.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Page.cs
=> Firefox: Pass page wait for tests

src/PlaywrightSharp.Tests/Page/PageSetExtraHttpHeadersTests.cs
=> firefox pass Page.setExtraHTTPHeaders

src/PlaywrightSharp.Firefox/FirefoxExecutionContext.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleScreenshotTests.cs, src/PlaywrightSharp.Tests/Page/ScreenshotTests.cs
=> Firefox: Pass ScreenshotTests

src/PlaywrightSharp.Abstractions/IElementHandle.cs, src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Tests/Mouse/MouseTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Input/KeyDefinitions.cs, src/PlaywrightSharp/Input/Keyboard.cs, src/PlaywrightSharp/Input/Mouse.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass MouseTests

src/PlaywrightSharp.Firefox/FirefoxBrowserContext.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Firefox/FirefoxTarget.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleClickTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleContentFrameTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleFillTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleHoverTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleOwnerFrameTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleScrollIntoViewIfNeededTests.cs, src/PlaywrightSharp.Tests/ElementHandle/ElementHandleVisibleRatioTests.cs
=> pass firefox elementhandle.spec.js

src/PlaywrightSharp.Abstractions/IElementHandle.cs, src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/IKeyboard.cs, src/PlaywrightSharp.Abstractions/TypeOptions.cs, src/PlaywrightSharp.Tests/Keyboard/KeyboardTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Input/Keyboard.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass KeyboardTests

src/PlaywrightSharp.Abstractions/IBrowserContext.cs, src/PlaywrightSharp.Abstractions/SetNetworkCookieParam.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Firefox/FirefoxBrowserContext.cs, src/PlaywrightSharp.Firefox/Protocol/Cookie.cs, src/PlaywrightSharp.Firefox/Protocol/CookieOptions.cs, src/PlaywrightSharp.Tests/BrowserContext/ClearCookiesTests.cs, src/PlaywrightSharp.Tests/BrowserContext/CookiesTests.cs, src/PlaywrightSharp.Tests/BrowserContext/SetCookiesTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/IBrowserContextDelegate.cs
=> Firefox: Pass browser context cookie tests

src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Assets/file-to-upload.txt, src/PlaywrightSharp.Tests/Input/InputTests.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp/Dom.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/FilePayload.cs, src/PlaywrightSharp/IPageDelegate.cs
=> Chromium: Pass input tests

src/PlaywrightSharp.Abstractions/NetworkCookie.cs, src/PlaywrightSharp.Abstractions/SameSite.cs, src/PlaywrightSharp.Abstractions/SetNetworkCookieParam.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/Protocol/Network/Cookie.cs, src/PlaywrightSharp.Chromium/Protocol/Network/CookieParam.cs, src/PlaywrightSharp.Chromium/Protocol/Protocol.Generated.cs, src/PlaywrightSharp.Firefox/Protocol/Cookie.cs, src/PlaywrightSharp.Firefox/Protocol/CookieOptions.cs, src/PlaywrightSharp.ProtocolTypesGenerator/StandardProtocolTypesGeneratorBase.cs, src/PlaywrightSharp.Tests/BrowserContext/ClearCookiesTests.cs, src/PlaywrightSharp.Tests/BrowserContext/CookiesTests.cs, src/PlaywrightSharp.Tests/BrowserContext/SetCookiesTests.cs, src/PlaywrightSharp.Webkit/Protocol/Protocol.Generated.cs, src/PlaywrightSharp/FrameManager.cs, src/PlaywrightSharp/LifecycleWatcher.cs
=> Chromium: Pass cookies tests

src/PlaywrightSharp.Abstractions/IElementHandle.cs, src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/ISelectors.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllXpathTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandlesQuerySelectorEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllXpathTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/SelectorsRegisterTests.cs, src/PlaywrightSharp.Tests/QuerySelector/TextSelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ZselectorTests.cs, src/PlaywrightSharp/Dom.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/FrameExecutionContext.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Resources/injectedSource.ts, src/PlaywrightSharp/Resources/zsSelectorEngineSource.ts, src/PlaywrightSharp/Selectors.cs
=> Firefox: Pass queryselector tests 

src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Input/PageWaitForFileChooserIsMultipleTests.cs, src/PlaywrightSharp.Tests/Input/PageWaitForFileChooserTests.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageWaitForFileChooserIsMultipleTests and PageWaitForFileChooserTests tests

src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllXpathTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandlesQuerySelectorEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllXpathTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/SelectorsRegisterTests.cs, src/PlaywrightSharp.Tests/QuerySelector/TextSelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ZselectorTests.cs
=> Chromium: Pass QuerySelector tests

src/PlaywrightSharp.Abstractions/ResourceType.cs, src/PlaywrightSharp.Chromium/ChromiumInterceptableRequest.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/Protocol/ProtocolConverters.cs, src/PlaywrightSharp.Firefox/FirefoxNetworkManager.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Frame/GoToTests.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/NavigationException.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Request.cs, src/PlaywrightSharp/Response.cs
=> Pass: Chromium Frame.GoTo tests

src/PlaywrightSharp.Chromium/ChromiumExecutionContext.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.TestServer/SimpleServer.cs, src/PlaywrightSharp.Tests/Frame/WaitForNavigationTests.cs, src/PlaywrightSharp.Tests/Page/WaitForNavigationTests.cs, src/PlaywrightSharp/FrameManager.cs, src/PlaywrightSharp/Helpers/StringExtensions.cs, src/PlaywrightSharp/LifecycleWatcher.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Request.cs, src/PlaywrightSharp/TimeoutSettings.cs, src/PlaywrightSharp/Transport/SlowMoTransport.cs, src/PlaywrightSharp/Transport/WebSocketTransport.cs
=> Chromium: Pass WaitForNavigation tests

src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Tests/Page/WaitForLoadStateTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass WaitForLoadState tests

src/PlaywrightSharp.Tests/Page/NetworkIdleTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/FrameManager.cs
=> Chromium: Pass network idle tests

src/PlaywrightSharp.Tests/Page/ReloadTests.cs
=> Chromium: Pass reload tests

src/PlaywrightSharp.Tests/Page/GoBackTests.cs
=> Chromium: Pass Go Back Tests

src/PlaywrightSharp.Chromium/ChromiumInterceptableRequest.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Firefox/FirefoxNetworkManager.cs, src/PlaywrightSharp.Firefox/FirefoxRequest.cs, src/PlaywrightSharp.Tests/Page/GoToTests.cs, src/PlaywrightSharp/FrameManager.cs, src/PlaywrightSharp/LifecycleWatcher.cs, src/PlaywrightSharp/Request.cs
=> Chromium: Pass Go to tests

src/PlaywrightSharp.Tests/Page/Events/PageEventsRequestTests.cs
=> Chromium: Pass PageEventRequest tests

src/PlaywrightSharp.Tests/Page/Network/RequestFrameTests.cs
=> Chromium: Pass RequestFrameTests

src/PlaywrightSharp.Tests/Page/Network/RequestHeadersTests.cs
=> Chromium: Pass RequestHeadersTests

src/PlaywrightSharp.Tests/Page/Network/RequestIsNavigationRequestTests.cs, src/PlaywrightSharp/Request.cs
=> Chromium: Pass RequestIsNavigationRequestTests

src/PlaywrightSharp.Tests/Page/Network/RequestPostDataTests.cs
=> Chromium: Pass RequestPostDataTests

src/PlaywrightSharp.Tests/Page/Network/ResponseHeadersTests.cs
=> Chromium: Pass ResponseHeadersTests

src/PlaywrightSharp.Abstractions/IResponse.cs, src/PlaywrightSharp.Tests/Page/Network/ResponseJsonTests.cs, src/PlaywrightSharp/Response.cs
=> Chromium: Pass ResponseJsonTests

src/PlaywrightSharp.Tests/Page/Network/ResponseStatusTextTests.cs
=> Chromium: Pass ResponseStatusTextTests

src/PlaywrightSharp.Tests/Page/PageSetExtraHttpHeadersTests.cs
=> Chromium: Pass PageSetExtraHttpHeadersTests

src/PlaywrightSharp.Tests/Page/WebSocketTests.cs
=> Chromium: Pass WebSocketTests

src/PlaywrightSharp.Firefox/FirefoxInterceptableRequest.cs, src/PlaywrightSharp.Firefox/FirefoxNetworkManager.cs, src/PlaywrightSharp.Firefox/FirefoxRequest.cs, src/PlaywrightSharp.Tests/Page/Network/RequestFrameTests.cs, src/PlaywrightSharp.Tests/Page/Network/RequestHeadersTests.cs, src/PlaywrightSharp.Tests/Page/Network/RequestIsNavigationRequestTests.cs, src/PlaywrightSharp.Tests/Page/Network/RequestPostDataTests.cs, src/PlaywrightSharp.Tests/Page/Network/ResponseHeadersTests.cs
=> Firefox: pass network tests

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/Credential.cs, src/PlaywrightSharp.Chromium/Protocol/Protocol.Generated.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.ProtocolTypesGenerator/StandardProtocolTypesGeneratorBase.cs, src/PlaywrightSharp.Tests/Page/Network/NetworkEventsTests.cs, src/PlaywrightSharp.Webkit/Protocol/Protocol.Generated.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass NetworkEventsTests

src/PlaywrightSharp.TestServer/SimpleCompressionMiddleware.cs, src/PlaywrightSharp.Tests/Page/Network/ResponseTextTests.cs
=> Chromium: Pass ResponseTextTests

src/PlaywrightSharp.Tests/RequestInterception/IgnoreHttpsErrorsTests.cs
=> Chromium: Pass IgnoreHttpsErrorsTests

src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/Credential.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Page/PageAuthenticateTests.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageAuthenticateTests

src/PlaywrightSharp.Abstractions/Payload.cs, src/PlaywrightSharp.Chromium/ChromiumInterceptableRequest.cs, src/PlaywrightSharp.Tests/RequestInterception/IgnoreHttpsErrorsTests.cs, src/PlaywrightSharp.Tests/RequestInterception/InterceptionContinueTests.cs
=> Chromium: Pass InterceptionContinueTests

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/RequestInterception/InterceptionSetOfflineModeTests.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass InterceptionSetOfflineModeTests

src/PlaywrightSharp.Tests/RequestInterception/InterceptionVsIsNavigationRequestTests.cs
=> Chromium: Pass InterceptionVsIsNavigationRequestTests

src/PlaywrightSharp.Abstractions/ResponseData.cs, src/PlaywrightSharp.Chromium/ChromiumInterceptableRequest.cs, src/PlaywrightSharp.Chromium/PlaywrightSharp.Chromium.csproj, src/PlaywrightSharp.Tests/RequestInterception/InterceptionFulfillTests.cs, src/PlaywrightSharp/Request.cs
=> Chromium: Pass InterceptionFulfillTests

src/PlaywrightSharp.Tests/RequestInterception/PageSetCacheEnabledTests.cs
=> Chromium: Pass PageSetCacheEnabledTests

src/PlaywrightSharp.Chromium/ChromiumInterceptableRequest.cs, src/PlaywrightSharp.Chromium/Protocol/ProtocolConverters.cs, src/PlaywrightSharp.Tests/Page/NetworkIdleTests.cs, src/PlaywrightSharp.Tests/RequestInterception/PageSetRequestInterceptionTests.cs
=> Chromium: Pass PageSetRequestInterceptionTests

src/PlaywrightSharp.Tests/Frame/FrameEvaluateHandleTests.cs
=> firefox: pass FrameEvaluateHandleTests

src/PlaywrightSharp.Tests/Frame/FrameManagementTests.cs
=> Firefox: Pass FrameManagementTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Frame/GoToTests.cs
=> Firefox: Pass GoToTests

src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/Protocol/ProtocolConverters.cs, src/PlaywrightSharp.Tests/Page/Events/DialogTests.cs, src/PlaywrightSharp/Dialog.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass DialogTests

src/PlaywrightSharp.Tests/Frame/WaitForNavigationTests.cs
=> firefox: pass WaitForNavigationTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Input/InputTests.cs
=> firefox: pass InputTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Input/PageWaitForFileChooserIsMultipleTests.cs
=> firefox: pass PageWaitForFileChooserIsMultipleTests

src/PlaywrightSharp.Tests/BrowserContext/DefaultBrowserContextTests.cs, src/PlaywrightSharp.Tests/RequestInterception/PageSetRequestInterceptionTests.cs
=> Chromium: Pass DefaultBrowserContextTests

src/PlaywrightSharp.Abstractions/BrowserContextOptions.cs, src/PlaywrightSharp.Abstractions/ContextPermission.cs, src/PlaywrightSharp.Abstractions/GeolocationOption.cs, src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Tests/BrowserContext/GeolocationTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/FrameManager.cs
=> Chromium: Pass Geolocation tests

src/PlaywrightSharp.Abstractions/ColorScheme.cs, src/PlaywrightSharp.Abstractions/ConsoleMessage.cs, src/PlaywrightSharp.Abstractions/MediaType.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/BrowserContext/TimezoneTests.cs, src/PlaywrightSharp.Tests/Page/EmulateMediaColorSchemeTests.cs, src/PlaywrightSharp.Tests/Page/EmulateMediaTypeTests.cs, src/PlaywrightSharp.Tests/Page/EmulateTests.cs, src/PlaywrightSharp.Tests/Page/ViewportTests.cs, src/PlaywrightSharp/Helpers/EnumHelper.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PageState.cs
=> Chromium: Pass Emulation tests

src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpWebLoaderCollection.cs, src/PlaywrightSharp.Tests/Playwright/WebTests.cs
closes #77
closes #118 
closes #150
=> Ignore WebTests

src/PlaywrightSharp.Tests/BrowserContext/DefaultBrowserContextTests.cs
=> Firefox: Pass DefaultBrowserContextTests

src/PlaywrightSharp.Tests/BrowserContext/IgnoreHttpsErrorsTests.cs
=> firefox: pass IgnoreHttpsErrorsTests

src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Firefox/FirefoxBrowserContext.cs, src/PlaywrightSharp.Firefox/Helper/FirefoxConverter.cs, src/PlaywrightSharp.Tests/BrowserContext/PermissionsTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/IBrowserContextDelegate.cs
=> firefox: pass PermissionsTests

src/PlaywrightSharp.Abstractions/ConsoleType.cs, src/PlaywrightSharp.Tests/Input/PageWaitForFileChooserTests.cs
=> firefox: pass PageWaitForFileChooserTests

src/PlaywrightSharp.Firefox/FirefoxBrowser.cs, src/PlaywrightSharp.Tests/Launcher/ConnectTests.cs
=> firefox: pass ConnectTests

src/PlaywrightSharp.Tests/Keyboard/KeyboardTests.cs
=> firefox: pass KeyboardTests

src/PlaywrightSharp.Tests/Mouse/MouseTests.cs
=> firefox: pass MouseTests

src/PlaywrightSharp.Tests/Frame/FrameWaitForFunctionTests.cs, src/PlaywrightSharp/Dom.cs, src/PlaywrightSharp/Frame.cs
=> Chromium: Pass FrameWaitForFunctionTests

src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Tests/Frame/WaitForSelectorEvaluateTests.cs, src/PlaywrightSharp/Dom.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass WaitForSelectorEvaluateTests

src/PlaywrightSharp.Tests/Page/PageWaitForTests.cs
=> Chromium: Pass PageWaitForTests

src/PlaywrightSharp.Tests/Frame/WaitForSelectorTests.cs, src/PlaywrightSharp/Frame.cs
=> Chromium: Pass WaitForSelectorTests

src/PlaywrightSharp.Tests/Frame/WaitForSelectorXPathTests.cs, src/PlaywrightSharp/Frame.cs
=> Chromium: Pass WaitForSelectorXPathTests

src/PlaywrightSharp.Firefox/FirefoxAXNode.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Accessibility/AccessibilityTests.cs, src/PlaywrightSharp.Tests/Accessibility/PlainTextContentEditableTests.cs, src/PlaywrightSharp.Tests/Accessibility/RootOptionTests.cs
=> Firefox: Pass accessibility tests

src/PlaywrightSharp.Tests/RequestInterception/PageSetRequestInterceptionTests.cs
=> improve PageSetRequestInterceptionTests.ShouldWorkWithEqualRequests test

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Abstractions/IWorker.cs, src/PlaywrightSharp.Chromium/ChromiumConnection.cs, src/PlaywrightSharp.Chromium/ChromiumNetworkManager.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Page/WorkerTests.cs, src/PlaywrightSharp/ExecutionContext.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Worker.cs
=> Chromium: Pass worker tests

src/PlaywrightSharp.Chromium/ChromiumBrowserType.cs, src/PlaywrightSharp.Chromium/Messaging/WSEndpointResponse.cs, src/PlaywrightSharp.Tests/Chromium/Launcher/BrowserUrlOptionTests.cs
=> Chromium: Pass BrowserUrlOptionTests

src/PlaywrightSharp.Tests/Chromium/Launcher/WebSocketOptionsTests.cs
=> Chromium: Pass WebSocketOptionsTests

src/PlaywrightSharp.Tests/Frame/FrameWaitForFunctionTests.cs
=> Firefox: Pass FrameWaitForFunctionTests

src/PlaywrightSharp.Tests/Frame/WaitForSelectorEvaluateTests.cs
=> Firefox: pass WaitForSelectorEvaluateTests

src/PlaywrightSharp.Tests/Frame/WaitForSelectorXPathTests.cs
=> Firefox: pass WaitForSelectorXPathTests

src/PlaywrightSharp.Tests/Frame/WaitForSelectorTests.cs
=> Firefox: pass WaitForSelectorTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp/FrameManager.cs
=> Null check on watchers

src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Tests/Chromium/Browser/TargetEventsTests.cs
=> Chromium: Pass TargetEventsTests

src/PlaywrightSharp.Tests/Chromium/ChromiumSpecificPageTests.cs
=> Chromium: Pass ChromiumSpecificPageTests

src/PlaywrightSharp.Abstractions/ICoverage.cs, src/PlaywrightSharp.Abstractions/IFrame.cs, src/PlaywrightSharp.Chromium/CSSCoverage.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/Coverage.cs, src/PlaywrightSharp.Chromium/CoverageEntryPoint.cs, src/PlaywrightSharp.Chromium/JSCoverage.cs, src/PlaywrightSharp.Chromium/Protocol/Protocol.Generated.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Chromium/CSSCoverageTests.cs, src/PlaywrightSharp.Tests/Chromium/JSCoverageTests.cs, src/PlaywrightSharp.Tests/Chromium/ResetOnNavigationTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass coverage tests

src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Tests/Chromium/OopifTests.cs
=> Chromium: Pass OopifTests

src/PlaywrightSharp.Abstractions/IBrowser.cs, src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Firefox/FirefoxBrowser.cs, src/PlaywrightSharp.Tests/Chromium/TargetTests.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass Target tests

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Abstractions/MarginOptions.cs, src/PlaywrightSharp.Abstractions/PaperFormat.cs, src/PlaywrightSharp.Abstractions/PdfOptions.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumPdf.cs, src/PlaywrightSharp.Chromium/ProtocolStreamReader.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Chromium/Browser/TargetEventsTests.cs, src/PlaywrightSharp.Tests/Chromium/ChromiumSpecificPageTests.cs, src/PlaywrightSharp.Tests/Chromium/HeadfulTests.cs, src/PlaywrightSharp.Tests/Chromium/Launcher/BrowserUrlOptionTests.cs, src/PlaywrightSharp.Tests/Chromium/Launcher/WebSocketOptionsTests.cs, src/PlaywrightSharp.Tests/Chromium/PdfTests.cs, src/PlaywrightSharp/Helpers/AsyncFileHelper.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PDF tests

src/PlaywrightSharp.Tests/Chromium/WaitForTargetTests.cs
=> Chromium: Pass WaitForTargetTests

src/PlaywrightSharp.Chromium/ChromiumExecutionContext.cs, src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumSession.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Chromium/JSCoverage.cs, src/PlaywrightSharp.Tests/Chromium/SessionTests.cs
=> Chromium: Pass session tests

src/PlaywrightSharp.Chromium/ChromiumBrowserContext.cs, src/PlaywrightSharp.Tests/BrowserContext/PermissionsTests.cs
=> Chromium: Pass PermissionsTests

src/PlaywrightSharp.Abstractions/IBrowser.cs, src/PlaywrightSharp.Abstractions/TracingOptions.cs, src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Firefox/FirefoxBrowser.cs, src/PlaywrightSharp.Tests/Chromium/TracingTests.cs
=> Chromium: Pass TracingTests

src/PlaywrightSharp.Tests/Launcher/ExecutablePathTests.cs
=> Firefox: pass ExecutablePathTests

src/PlaywrightSharp.Chromium/ChromiumBrowser.cs, src/PlaywrightSharp.Tests/Browser/IsConnectedTests.cs
=> Chromium: Pass IsConnectedTests

src/PlaywrightSharp.Tests/Capabilities/CapabilitiesTests.cs
=> Chromium: Pass CapabilitiesTests

src/PlaywrightSharp.Tests/Frame/FrameEvaluateTests.cs, src/PlaywrightSharp/Frame.cs
=> Chromium: Pass FrameEvaluateTests

src/PlaywrightSharp.Abstractions/IPage.cs, src/PlaywrightSharp.Tests/Page/Events/PageEventsDOMContentLoadedTests.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageEventsDOMContentLoadedTests

src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Tests/Page/Events/PageEventsErrorTests.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageEventsErrorTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsLoadTests.cs
=> Chromium: Pass PageEventsLoadTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsPopupTests.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageEventsPopupTests

src/PlaywrightSharp.Tests/Launcher/LaunchTests.cs
=> Firefox: pass LaunchTests

src/PlaywrightSharp.Tests/Launcher/LaunchWebSocketOptionTests.cs
=> Firefox: pass LaunchWebSocketOptionTests

src/PlaywrightSharp.Tests/Launcher/NameTests.cs
=> Firefox: pass NameTests

src/PlaywrightSharp.Tests/Page/PageAddScriptTagTests.cs
=> Chromium: Pass PageAddScriptTagTests

src/PlaywrightSharp.Tests/Page/PageAddStyleTagTests.cs
=> Chromium: Pass PageAddStyleTagTests

src/PlaywrightSharp.Tests/Launcher/UserDataDirTests.cs
=> Firefox: pass UserDataDirTests

src/PlaywrightSharp.Tests/Page/PageCloseTests.cs
=> Chromium: Pass PageCloseTests

src/PlaywrightSharp.Tests/Page/PageExposeFunctionTests.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageExposeFunctionTests

src/PlaywrightSharp.Tests/Page/PageFillTests.cs
=> Chromium: Pass PageFillTests

src/PlaywrightSharp.Chromium/ChromiumPage.cs, src/PlaywrightSharp.Chromium/ChromiumTarget.cs, src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Tests/Page/PageOpenerTests.cs, src/PlaywrightSharp/IPageDelegate.cs, src/PlaywrightSharp/Page.cs
=> Chromium: Pass PageOpenerTests

src/PlaywrightSharp.Tests/Page/PageBrowserContextTests.cs
=> Chromium: Pass PageBrowserContextTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Firefox/Helper/FirefoxConverter.cs, src/PlaywrightSharp.Tests/Page/EmulateMediaColorSchemeTests.cs
=> Firefox: pass EmulateMediaColorSchemeTests

src/PlaywrightSharp.Tests/Page/Network/ResponseTextTests.cs
closes #112 
this is the last test class of the network tests
=> Firefox: pass ResponseTextTests

src/PlaywrightSharp.Firefox/FirefoxExecutionContext.cs, src/PlaywrightSharp.Firefox/Protocol/RemoteObject.cs, src/PlaywrightSharp.Tests/Page/Events/PageEventsConsoleTests.cs
=> Firefox: pass PageEventsConsoleTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsCloseTests.cs
=> Firefox: pass PageEventsCloseTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Firefox/Helper/FirefoxConverter.cs, src/PlaywrightSharp.Tests/Page/Events/DialogTests.cs
=> Firefox: pass DialogTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsDOMContentLoadedTests.cs
=> Firefox: pass PageEventsDOMContentLoadedTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsErrorTests.cs
=> Firefox: skip PageEventsErrorTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsLoadTests.cs
=> Firefox: pass PageEventsLoadTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsPopupTests.cs
=> Firefox: pass PageEventsPopupTests

src/PlaywrightSharp.Tests/Page/PageSetContentTests.cs
=> Chromium: Pass PageSetContentTests

src/PlaywrightSharp.Tests/Page/PageWaitForResponseTests.cs
=> Chromium: Pass PageWaitForResponseTests

src/PlaywrightSharp.Tests/Page/PageWaitForRequestTests.cs
=> Chromium: Pass PageWaitForRequestTests

src/PlaywrightSharp.Tests/Page/PageBrowserContextTests.cs
=> Firefox: pass PageBrowserContextTests

src/PlaywrightSharp.Tests/Page/PageCloseTests.cs
=> Firefox: pass PageCloseTests

src/PlaywrightSharp.Tests/Page/PageExposeFunctionTests.cs
=> Firefox: pass PageExposeFunctionTests

src/PlaywrightSharp.Tests/Page/PageFillTests.cs
=> Firefox: pass PageFillTests

src/PlaywrightSharp.Tests/Page/PageSelectTests.cs
=> Firefox: pass PageSelectTests

src/PlaywrightSharp.Tests/Page/PageUrlTests.cs
=> Firefox: pass PageUrlTests

src/PlaywrightSharp.Tests/Page/ReloadTests.cs
=> Firefox: pass ReloadTests

src/PlaywrightSharp.Tests/Page/NetworkIdleTests.cs
=> Firefox: pass NetworkIdleTests

src/PlaywrightSharp.Tests/Capabilities/CapabilitiesTests.cs
=> Firefox: pass CapabilitiesTests

src/PlaywrightSharp.Tests/Frame/FrameEvaluateTests.cs
=> Firefox: pass FrameEvaluateTests

src/PlaywrightSharp.Tests/Page/WaitForLoadStateTests.cs
closes #111 (once #478 is merged)
=> Firefox: pass WaitForLoadStateTests

src/PlaywrightSharp.Firefox/FirefoxExecutionContext.cs, src/PlaywrightSharp.Firefox/Helper/JsonHelper.cs, src/PlaywrightSharp.Firefox/Helper/RemoteObjectJsonConverter.cs, src/PlaywrightSharp.Firefox/Protocol/RemoteObject.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleAsElementTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleGetPropertiesTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleGetPropertyTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleJsonValueTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleToStringTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/PageEvaluateHandleTests.cs
=> Firefox: pass jshandle.spec

src/PlaywrightSharp.Tests/Page/PageAddStyleTagTests.cs
=> Firefox: pass PageAddStyleTagTests

src/PlaywrightSharp.Tests/Page/PageAddScriptTagTests.cs
=> Firefox: pass PageAddScriptTagTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Firefox/FirefoxTarget.cs, src/PlaywrightSharp.Tests/Page/PageOpenerTests.cs
=> Firefox: pass PageOpenerTests

src/PlaywrightSharp.Firefox/FirefoxPage.cs, src/PlaywrightSharp.Firefox/FirefoxSession.cs, src/PlaywrightSharp.Firefox/Helper/FirefoxConverter.cs, src/PlaywrightSharp.Tests/Page/WorkerTests.cs
=> Firefox: Pass Worker tests

src/PlaywrightSharp.Abstractions/BrowserTypeBase.cs, src/PlaywrightSharp.Chromium/ChromiumProcessManager.cs, src/PlaywrightSharp.Firefox/FirefoxProcessManager.cs, src/PlaywrightSharp.Tests.CloseMe/PlaywrightSharp.Tests.CloseMe.csproj, src/PlaywrightSharp.Tests.CloseMe/Program.cs, src/PlaywrightSharp.Tests.DumpIO/Program.cs, src/PlaywrightSharp.Tests/Launcher/LaunchTests.cs, src/PlaywrightSharp.Tests/Playwright/FixturesTests.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp.Tests/TestConstants.cs, src/PlaywrightSharp.sln
closes #101 
I ignored ShouldCloseTheBrowserWhenTheConnectedProcessCloses. I think we don't have the right tools in .NET to implement that. I created #611 in case someone wants to work on that.
=> Firefox: Pass fixtures tests

src/PlaywrightSharp.Tests/Page/Events/PageEventsPageErrorTests.cs
=> Firefox: Pass PageEventsPageErrorTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsRequestTests.cs
=> Firefox: Pass PageEventsRequestTests

src/PlaywrightSharp.Firefox/FirefoxBrowser.cs, src/PlaywrightSharp.Tests/Browser/CloseTests.cs
=> Firefox: Pass Close tests

src/PlaywrightSharp.Tests/RequestInterception/InterceptionFulfillTests.cs
=> Firefox: Pass InterceptionFulfillTests

src/PlaywrightSharp.Tests/RequestInterception/InterceptionSetOfflineModeTests.cs
=> Firefox: Pass InterceptionSetOfflineModeTests

src/PlaywrightSharp.Tests/RequestInterception/InterceptionVsIsNavigationRequestTests.cs
=> Firefox: Pass InterceptionVsIsNavigationRequestTests

src/PlaywrightSharp.Tests/RequestInterception/PageSetCacheEnabledTests.cs
=> Firefox: Pass PageSetCacheEnabledTests

src/PlaywrightSharp.Tests/RequestInterception/PageSetRequestInterceptionTests.cs
=> Firefox: Pass PageSetRequestInterceptionTests

src/PlaywrightSharp.Tests/Launcher/LaunchWebSocketOptionTests.cs
=> Skip ShouldFireDisconnectedWhenClosingWithWebSocket on Firefox linux

src/PlaywrightSharp.Tests/BrowserContext/BrowserContextPagesTests.cs
=> Pass BrowserContextPagesTests

src/PlaywrightSharp.Tests/Browser/BrowserNewPageTests.cs, src/PlaywrightSharp.Tests/BrowserContext/BrowserContextExposeBindingTests.cs, src/PlaywrightSharp/BindingCall.cs, src/PlaywrightSharp/BindingSource.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/IBrowserContext.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/BindingCallChannel.cs, src/PlaywrightSharp/Transport/Channels/BrowserContextBindingCallEventArgs.cs, src/PlaywrightSharp/Transport/Channels/BrowserContextChannel.cs, src/PlaywrightSharp/Transport/Protocol/BindingCallInitializer.cs
=> Pass BrowserContextExposeBindingTests

src/PlaywrightSharp.Tests/Accessibility/AccessibilityTests.cs, src/PlaywrightSharp.Tests/Accessibility/PlainTextContentEditableTests.cs, src/PlaywrightSharp.Tests/Accessibility/RootOptionTests.cs, src/PlaywrightSharp/Accesibility.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/SerializedAXNode.cs, src/PlaywrightSharp/Transport/Channels/ChannelToGuidConverter.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> Pass accessibility tests

src/PlaywrightSharp.Tests/Autowaiting/AutoWaitingShouldNotHangTests.cs, src/PlaywrightSharp.Tests/Autowaiting/AutoWaitingTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/NavigatingActionWaitOptions.cs, src/PlaywrightSharp/NavigationOptions.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PageEvent.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs, src/PlaywrightSharp/Transport/Channels/FrameNavigatedEventArgs.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/WaitForNavigationOptions.cs
=> Pass autowaiting tests

src/PlaywrightSharp.Tests/Page/Events/DialogTests.cs, src/PlaywrightSharp.Tests/Page/PageCloseTests.cs, src/PlaywrightSharp/Dialog.cs, src/PlaywrightSharp/IDialog.cs, src/PlaywrightSharp/Transport/Protocol/DialogInitializer.cs
=> Pass dialog tests

src/PlaywrightSharp.Tests/DispatchEvent/ElementHandleDispatchEventClickTests.cs, src/PlaywrightSharp.Tests/DispatchEvent/PageDispatchEventClickTests.cs, src/PlaywrightSharp.Tests/DispatchEvent/PageDispatchEventDragTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs
=> Pass dispatch tests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleContentFrameTests.cs, src/PlaywrightSharp/ElementHandle.cs
=> Pass ElementHandleContentFrameTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleHoverTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> Pass ElementHandleHoverTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleFillTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/NavigatingActionWaitOptions.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> Pass ElementHandleFillTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleSelectTextTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> Pass ElementHandleSelectTextTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleCheckTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> Pass ElementHandleCheckTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleFocusTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> Pass ElementHandleFocusTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleSelectOptionTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> Pass ElementHandleSelectOptionTests

src/PlaywrightSharp.Tests/ElementHandle/ElementHandleClickTests.cs
=> Pass ElementHandleClickTests

src/PlaywrightSharp.Tests/DownloadsPath/DownloadsPathLaunchPersistentTests.cs, src/PlaywrightSharp.Tests/DownloadsPath/DownloadsPathLaunchTests.cs, src/PlaywrightSharp/LaunchOptions.cs, src/PlaywrightSharp/LaunchPersistentOptions.cs
=> Pass Download Path tests

src/PlaywrightSharp.Tests/Emulation/FocusTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Keyboard.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> Pass focus tests

src/PlaywrightSharp.Tests/Emulation/BrowserContextLocaleTests.cs, src/PlaywrightSharp.Tests/Emulation/BrowserContextTimezoneTests.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/Transport/Channels/PageChannelRequestEventArgs.cs
=> Pass BrowserContextLocaleTests

src/PlaywrightSharp.Tests/Helpers/RetryTestCase.cs, src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj, src/PlaywrightSharp.Tests/xunit.runner.json
Reverts hardkoded/playwright-sharp#694
It's not running all the tests
=> Revert "Don't timeout Retries"

src/PlaywrightSharp.Tests/Firefox/LauncherTests.cs, src/PlaywrightSharp/LaunchOptions.cs, src/PlaywrightSharp/LaunchPersistentOptions.cs
=> Pass Firefox launcher tests

src/PlaywrightSharp.Tests/Frame/FrameEvaluateHandleTests.cs
=> Pass FrameEvaluateHandleTests

src/PlaywrightSharp.Tests/Frame/FrameManagementTests.cs
=> Pass FrameManagementTests

src/PlaywrightSharp.Tests/Frame/FrameElementTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs
=> Pass FrameElementTests

src/PlaywrightSharp.Tests/Frame/FrameEvaluateTests.cs, src/PlaywrightSharp/Page.cs
=> Pass FrameEvaluateTests

src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserContextBaseTest.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserLoaderFixture.cs, src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpPageBaseTest.cs, src/PlaywrightSharp.Tests/BrowserContext/BrowserContextHttpCredentialsTests.cs, src/PlaywrightSharp.Tests/Input/PageWaitForFileChooserIsMultipleTests.cs, src/PlaywrightSharp.Tests/Input/PageWaitForFileChooserTests.cs, src/PlaywrightSharp.Tests/Page/PageClickTests.cs, src/PlaywrightSharp.Tests/xunit.runner.json, src/PlaywrightSharp/FileChooserEventArgs.cs, src/PlaywrightSharp/Helpers/TaskQueue.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/FileChooserChannelEventArgs.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/Transport/Connection.cs, src/PlaywrightSharp/Transport/IConnectionTransport.cs, src/PlaywrightSharp/Transport/StdIOTransport.cs, src/PlaywrightSharp/Transport/TransportClosedEventArgs.cs
=> Pass PageWaitForFileChooserTests and PageWaitForFileChooserIsMultiple

src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleJsonValueTests.cs
=> Pass JSHandleJsonValueTests

src/PlaywrightSharp.Tests/Frame/JsHandle/PageEvaluateHandleTests.cs, src/PlaywrightSharp/Transport/Converters/EvaluateArgumentValueConverter.cs
=> Pass PageEvaluateHandleTests

src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleGetPropertiesTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleGetPropertyTests.cs, src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleToStringTests.cs, src/PlaywrightSharp/JSHandle.cs, src/PlaywrightSharp/Transport/Channels/JSHandleChannel.cs, src/PlaywrightSharp/Transport/Connection.cs
=> Pass JSHandleGetPropertyTests

src/PlaywrightSharp.Tests/Page/PageCloseTests.cs, src/PlaywrightSharp/Page.cs
=> Pass PageCloseTests

src/PlaywrightSharp.Tests/Page/PageOpenerTests.cs
=> Pass PageOpenerTests

src/PlaywrightSharp.Tests/Frame/JsHandle/JSHandleAsElementTests.cs
=> Pass JSHandleAsElementTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsLoadTests.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> Pass PageEventsLoadTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsConsoleTests.cs
=> Pass PageEventsConsoleTests

src/PlaywrightSharp.Tests/Page/PageWaitForRequestTests.cs
=> Pass PageWaitForRequestTests

src/PlaywrightSharp.Tests/Page/PageWaitForEvent.cs
=> Pass PageWaitForEvent

src/PlaywrightSharp.Tests/Page/AsyncStacksTests.cs, src/PlaywrightSharp.Tests/Page/Events/PageEventsPageCrashTests.cs
=> Pass PageEventsPageCrashTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsDOMContentLoadedTests.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> Pass PageEventsDOMContentLoadedTests

src/PlaywrightSharp.Tests/Page/PageExposeBindingTests.cs
=> Pass PageExposeBindingTests

src/PlaywrightSharp.Tests/Page/PageExposeFunctionTests.cs, src/PlaywrightSharp/BindingCall.cs
=> Pass PageExposeFunctionTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsPageErrorTests.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PageErrorEventArgs.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> Pass PageEventsPageErrorTests

src/PlaywrightSharp.Tests/Page/PageWaitForResponseTests.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/RequestEventArgs.cs, src/PlaywrightSharp/Response.cs, src/PlaywrightSharp/ResponseEventArgs.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/Transport/Channels/PageChannelRequestEventArgs.cs, src/PlaywrightSharp/Transport/Protocol/ResponseInitializer.cs
=> Pass PageWaitForResponseTests

src/PlaywrightSharp.Tests/Page/PageSetContentTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs
=> Pass PageSetContentTests

src/PlaywrightSharp.Tests/Page/PageAddStyleTagTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs
=> Pass PageAddStyleTagTests

src/PlaywrightSharp.Tests/Page/PageBrowserContextTests.cs
=> Pass PageBrowserContextTests

src/PlaywrightSharp.Tests/Page/PageUrlTests.cs
=> Pass PageUrlTests

src/PlaywrightSharp.Tests/Page/Events/PageEventsCloseTests.cs
=> Pass PageEventsCloseTests

src/PlaywrightSharp.Tests/Page/PageAddScriptTagTests.cs
=> Pass PageAddScriptTagTests

src/PlaywrightSharp.Tests/Page/PageSelectOptionTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/SelectOption.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs, src/PlaywrightSharp/Transport/Converters/ChannelOwnerToGuidConverter.cs
=> Pass PageSelectOptionTests

src/PlaywrightSharp.Tests/Page/PageFillTests.cs
=> Pass PageFillTests

src/PlaywrightSharp.Tests/Page/PageFrameTests.cs
=> Pass PageFrameTests

src/PlaywrightSharp.Tests/Page/PageChannelTests.cs
=> Pass PageChannelTests

src/PlaywrightSharp.Tests/Page/UserAgentSanityTests.cs
=> Pass UserAgentSanityTests

src/PlaywrightSharp.Tests/Page/PageApiCoverageTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs
=> Pass PageApiCoverageTests

src/PlaywrightSharp.Tests/Popup/LinkNavigationTests.cs
=> Pass LinkNavigationTests

src/PlaywrightSharp.Tests/Popup/WindowOpenTests.cs, src/PlaywrightSharp/BindingCall.cs
=> Pass WindowOpenTests

src/PlaywrightSharp.Tests/BrowserContext/IgnoreHttpsErrorsTests.cs
=> Pass IgnoreHttpsErrorsTests

src/PlaywrightSharp.Tests/Launcher/HeadfulTests.cs
=> Pass HeadfulTests

src/PlaywrightSharp.Tests/Page/GoToTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Response.cs, src/PlaywrightSharp/Transport/Channels/BrowserContextChannel.cs, src/PlaywrightSharp/Transport/Channels/ChannelOwnerType.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/Transport/Protocol/ResponseInitializer.cs
=> Pass GoToTests

src/PlaywrightSharp.Tests/Page/NetworkIdleTests.cs, src/PlaywrightSharp/Frame.cs
=> Pass NetworkIdleTests

src/PlaywrightSharp.Tests/Page/WaitForLoadStateTests.cs
=> Pass WaitForLoadStateTests

src/PlaywrightSharp.Tests/Page/WaitForNavigationTests.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs, src/PlaywrightSharp/WaitForNavigationOptions.cs
=> Pass WaitForNavigationTests

src/PlaywrightSharp.Tests/Frame/WaitForLoadStateTests.cs
=> Pass Frame.WaitForLoadStateTests

src/PlaywrightSharp.Tests/Page/ClickNavigationTests.cs
=> Pass ClickNavigationTests

src/PlaywrightSharp.Tests/Page/PageReloadTests.cs
=> Pass PageReloadTests

src/PlaywrightSharp.Tests/Chromium/ChromiumSpecificPageTests.cs, src/PlaywrightSharp.Tests/Chromium/OopifTests.cs, src/PlaywrightSharp.Tests/Page/Events/PageEventsRequestTests.cs, src/PlaywrightSharp.Tests/Page/Network/NetworkEventsTests.cs, src/PlaywrightSharp.Tests/Page/Network/RequestFrameTests.cs, src/PlaywrightSharp.Tests/Page/Network/ResponseTextTests.cs, src/PlaywrightSharp.Tests/Page/WorkerTests.cs, src/PlaywrightSharp.Tests/RequestInterception/IgnoreHttpsErrorsTests.cs, src/PlaywrightSharp.Tests/RequestInterception/InterceptionContinueTests.cs, src/PlaywrightSharp.Tests/RequestInterception/InterceptionFulfillTests.cs, src/PlaywrightSharp.Tests/RequestInterception/InterceptionVsIsNavigationRequestTests.cs, src/PlaywrightSharp.Tests/RequestInterception/PageSetCacheEnabledTests.cs, src/PlaywrightSharp.Tests/RequestInterception/PageSetRequestInterceptionTests.cs, src/PlaywrightSharp.Tests/Webkit/ProvisionalTests.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/IRequest.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Payload.cs, src/PlaywrightSharp/Request.cs, src/PlaywrightSharp/RequestAbortErrorCode.cs, src/PlaywrightSharp/Transport/Channels/RequestChannel.cs
=> Pass PageEventsRequestTests

src/PlaywrightSharp.Tests/Page/Network/RequestHeadersTests.cs
=> Pass RequestHeadersTests

src/PlaywrightSharp.Tests/Page/Network/ResponseJsonTests.cs, src/PlaywrightSharp/Response.cs
=> Pass ResponseJsonTests

src/PlaywrightSharp.Tests/Page/Network/RequestPostDataTests.cs
=> Pass RequestPostDataTests

src/PlaywrightSharp.Tests/Page/Network/RequestPostDataJsonTests.cs, src/PlaywrightSharp/IRequest.cs, src/PlaywrightSharp/Request.cs
=> Pass RequestPostDataJsonTests

src/PlaywrightSharp.Tests/Multiclient/BrowserContextTests.cs
=> Pass Multiclient BrowserContextTests

src/PlaywrightSharp.Tests/Playwright/LoggerTests.cs
=> Pass LoggerTests

src/PlaywrightSharp.Tests/Multiclient/BrowserEventsDisconnected.cs
=> Pass BrowserEventsDisconnected

src/PlaywrightSharp.Tests/Multiclient/BrowserTypeConnectTests.cs
=> Pass multiclient BrowserTypeConnectTests

src/PlaywrightSharp.Tests/BrowserType/HttpProxyTests.cs, src/PlaywrightSharp.Tests/BrowserType/SocksProxyTests.cs, src/PlaywrightSharp/LaunchOptions.cs, src/PlaywrightSharp/LaunchPersistentOptions.cs, src/PlaywrightSharp/ProxySettings.cs
=> Pass proxy tests

src/PlaywrightSharp.Tests/Page/WorkerTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/IWorker.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PageEvent.cs, src/PlaywrightSharp/Transport/Channels/WorkerChannel.cs, src/PlaywrightSharp/Worker.cs
=> Pass WorkerTests

src/PlaywrightSharp.Tests/BrowserContext/GeolocationTests.cs, src/PlaywrightSharp.Tests/BrowserContext/LaunchPersistentContextTests.cs, src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/BrowserContextOptions.cs, src/PlaywrightSharp/Geolocation.cs, src/PlaywrightSharp/IBrowserContext.cs, src/PlaywrightSharp/IBrowserContextDelegate.cs, src/PlaywrightSharp/LaunchPersistentOptions.cs, src/PlaywrightSharp/Transport/Channels/BrowserContextChannel.cs
=> Rename GeolocationOption to Geolocation

.vscode/launch.json, .vscode/tasks.json, demos/PdfDemo/PdfDemo-Local.csproj, demos/PdfDemo/PdfDemo-Local.sln, demos/PdfDemo/Program.cs, demos/ScreenshotsDemo/Program.cs, demos/ScreenshotsDemo/ScreenshotsDemo-Local.csproj, demos/ScreenshotsDemo/ScreenshotsDemo-Local.sln, src/PlaywrightSharp/Transport/Connection.cs
Created two launch settings to launch the PDF and Screenshot Demos. 
I also added a task to run tests
=> VS Code setup

src/PlaywrightSharp.Tests/BrowserContext/BrowserContextBypassCSPTests.cs, src/PlaywrightSharp.Tests/BrowserContext/BrowserContextJavaScriptEnabledTests.cs, src/PlaywrightSharp.Tests/BrowserContext/LaunchPersistentContextTests.cs, src/PlaywrightSharp.Tests/DownloadsPath/DownloadsPathLaunchPersistentTests.cs, src/PlaywrightSharp.Tests/Emulation/BrowserContextLocaleTests.cs, src/PlaywrightSharp.Tests/Page/DownloadTests.cs, src/PlaywrightSharp.Tests/TestConstants.cs, src/PlaywrightSharp/Browser.cs, src/PlaywrightSharp/BrowserContextOptions.cs, src/PlaywrightSharp/BrowserType.cs, src/PlaywrightSharp/IBrowser.cs, src/PlaywrightSharp/IBrowserContext.cs, src/PlaywrightSharp/IBrowserType.cs, src/PlaywrightSharp/LaunchOptions.cs, src/PlaywrightSharp/LaunchPersistentOptions.cs, src/PlaywrightSharp/PlaywrightSharp.csproj, src/PlaywrightSharp/Transport/Channels/BrowserChannel.cs, src/PlaywrightSharp/Transport/Channels/BrowserTypeChannel.cs, src/PlaywrightSharp/ViewportSize.cs
=> Options refactor

src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/IJSHandle.cs, src/PlaywrightSharp/JSHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs, src/PlaywrightSharp/Transport/Channels/JSHandleChannel.cs
=> v1.4 Move EvaluateHandleAsync to JSHandle

src/PlaywrightSharp.Tests/ElementHandleWaitForElementStateTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/ElementState.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs
=> v1.4 Introduce WaitForElementStateAsync

src/PlaywrightSharp.Tests/Frame/FrameManagementTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/Page.cs
=> v1.4 Rename Detached to IsDetached add WaitForTimeout

src/PlaywrightSharp.Tests/Page/ScreenshotTests.cs, src/PlaywrightSharp.Tests/TestUtils.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs
=> v1.4 Rename Viewport to ViewportSize

src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpPageBaseTest.cs, src/PlaywrightSharp.Tests/Page/Events/PageEventsPageCrashTests.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PageEvent.cs
=> v1.4 Rename Crashed to Crash

src/PlaywrightSharp.Tests/Accessibility/RootOptionTests.cs, src/PlaywrightSharp.Tests/Capabilities/CapabilitiesTests.cs, src/PlaywrightSharp.Tests/ElementHandleWaitForElementStateTests.cs, src/PlaywrightSharp.Tests/Frame/FrameElementTests.cs, src/PlaywrightSharp.Tests/Frame/GoToTests.cs, src/PlaywrightSharp.Tests/Keyboard/KeyboardTests.cs, src/PlaywrightSharp.Tests/Mouse/DragAndDropTests.cs, src/PlaywrightSharp.Tests/Page/PageClickTests.cs, src/PlaywrightSharp.Tests/Page/PageFillTests.cs, src/PlaywrightSharp.Tests/Page/PageFocusTests.cs, src/PlaywrightSharp.Tests/Page/PageSelectOptionTests.cs, src/PlaywrightSharp.Tests/Page/PageSetContentTests.cs, src/PlaywrightSharp.Tests/PageSetInputFilesTests.cs, src/PlaywrightSharp.Tests/Popup/PageEventsPopupTests.cs, src/PlaywrightSharp.Tests/QuerySelector/AttributeSelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/CssSelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorAllEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/ElementHandleQuerySelectorTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorAllEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/PageQuerySelectorEvaluateTests.cs, src/PlaywrightSharp.Tests/QuerySelector/TextSelectorTests.cs, src/PlaywrightSharp.Tests/RequestInterception/PageRouteTests.cs, src/PlaywrightSharp.Tests/WaitForSelector2Tests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs
=> Rename QuerySelectorEvaluate and QuerySelectorAllEvaluate

src/PlaywrightSharp.Tests/BrowserTests.cs, src/PlaywrightSharp/Browser.cs, src/PlaywrightSharp/IBrowser.cs, src/PlaywrightSharp/Transport/ConnectionScope.cs, src/PlaywrightSharp/Transport/Protocol/BrowserInitializer.cs
=> v1.4 Introduce Browser.Version

src/PlaywrightSharp.Tests/DownloadTests.cs, src/PlaywrightSharp/Download.cs, src/PlaywrightSharp/Transport/Channels/DownloadChannel.cs
=> v1.4 Introduce Download.SaveAsAsync

src/PlaywrightSharp.Tests/HeadfulTests.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> v1.4 Introduce BringToFrontAsync

README.md
=> README: Prettify header

src/PlaywrightSharp.Tests/PdfTests.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> Fix PDF generation

docfx_project/docfx.json, docfx_project/examples/Page.ScreenshotAsync.md, docfx_project/examples/index.md, docfx_project/examples/toc.yml, docfx_project/toc.yml
built locally to see, looks good!
based on https://www.puppeteersharp.com/examples/index.html
=> add examples to docs

.github/workflows/tests.yml
it can only go wrong
Closes #833
=> devops: run tests on all operating systems

src/PlaywrightSharp/Transport/ChannelOwnerBase.cs, src/PlaywrightSharp/Transport/Channels/IChannelOwner.cs, src/PlaywrightSharp/Transport/Connection.cs
=> Process dispose message

demos/PdfDemo/PdfDemo-Local.csproj, demos/PdfDemo/Program.cs, docfx_project/examples/Playwright.Logger.md, docfx_project/examples/toc.yml, src/PlaywrightSharp/Playwright.cs, src/PlaywrightSharp/Transport/Connection.cs, src/PlaywrightSharp/Transport/IConnectionTransport.cs, src/PlaywrightSharp/Transport/LogReceivedEventArgs.cs, src/PlaywrightSharp/Transport/StdIOTransport.cs
=> feat(playwright): Log debug info

src/Common/PackageInfo.props, src/PlaywrightSharp.Tests/PdfTests.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Margin.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PaperFormat.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs
=> fix(page): PaperFormat should be an enum

src/PlaywrightSharp/Transport/Connection.cs
=> fix(connection): remove timeout from connection tasks

src/PlaywrightSharp/Transport/Connection.cs
=> chore(connection): unzip drivers in a platform specific directory

src/PlaywrightSharp/PlaywrightSharp.csproj, src/PlaywrightSharp/Transport/Connection.cs, src/tools/DriverDownloader/Program.cs
=> chore(driver): 32-bit support

docfx_project/documentation/Page.Download.md
=> doc(page): add download example

src/PlaywrightSharp/PlaywrightSharp.csproj
=> chore: drop netstandard 2.1

src/PlaywrightSharp/Transport/Connection.cs
=> fix(connection): Throw connection close exception on wait for object

src/PlaywrightSharp.Tests/ResourceTimingTests.cs, src/PlaywrightSharp/IRequest.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Request.cs, src/PlaywrightSharp/ResourceTiming.cs, src/PlaywrightSharp/Response.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/Transport/Channels/PageChannelRequestEventArgs.cs, src/PlaywrightSharp/Transport/Protocol/ResponseInitializer.cs
=> feat(request): introduce timing property

src/PlaywrightSharp.Tests/ScreencastTests.cs, src/PlaywrightSharp/Browser.cs, src/PlaywrightSharp/BrowserContextOptions.cs, src/PlaywrightSharp/BrowserType.cs, src/PlaywrightSharp/Chromium/ChromiumBrowser.cs, src/PlaywrightSharp/Chromium/ChromiumBrowserType.cs, src/PlaywrightSharp/Chromium/IChromiumBrowser.cs, src/PlaywrightSharp/Chromium/IChromiumBrowserType.cs, src/PlaywrightSharp/IBrowser.cs, src/PlaywrightSharp/IBrowserType.cs, src/PlaywrightSharp/LaunchPersistentOptions.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/RecordVideoOptions.cs, src/PlaywrightSharp/Video.cs
=> feat(screencast): new recordVideo option

src/Common/PackageInfo.props, src/PlaywrightSharp.TestServer/SimpleServer.cs, src/PlaywrightSharp.Tests/WebSocketTests.cs, src/PlaywrightSharp/Helpers/StringExtensions.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/IWebSocket.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/PageEvent.cs, src/PlaywrightSharp/Transport/Channels/PageChannel.cs, src/PlaywrightSharp/Transport/Channels/WebSocketChannel.cs, src/PlaywrightSharp/Transport/Connection.cs, src/PlaywrightSharp/Transport/Protocol/WebSocketInitializer.cs, src/PlaywrightSharp/WebSocket.cs, src/PlaywrightSharp/WebSocketErrorEventArgs.cs, src/PlaywrightSharp/WebSocketEvent.cs, src/PlaywrightSharp/WebSocketEventArgs.cs, src/PlaywrightSharp/WebSocketFrameEventArgs.cs
=> feat(page): introduce websockets

README.md, demos/PdfDemo/PdfDemo.csproj, demos/PdfDemo/Program.cs, demos/ScreenshotsDemo/Program.cs, demos/ScreenshotsDemo/ScreenshotsDemo.csproj, docfx_project/documentation/Page.Download.md, docfx_project/documentation/Page.ScreenshotAsync.md, docfx_project/documentation/index.md, src/PlaywrightSharp.Demo/Program.cs, src/PlaywrightSharp/Playwright.cs
closes #1017 
closes #969
Also added docs for deployment.
=> doc: remove InstallAsync from docs

README.md, docfx_project/documentation/index.md, src/PlaywrightSharp/PlaywrightSharp.csproj, src/tools/DriverDownloader/Program.cs
=> devops: update browsers table on driver update

src/Common/PackageInfo.props, src/PlaywrightSharp/build/netstandard2.0/PlaywrightSharp.targets
=> chore: add copy targets for Xamarin.Mac

src/PlaywrightSharp/build/netstandard2.0/PlaywrightSharp.targets
=> chore(driver): support .NET Framework using mono

src/PlaywrightSharp/Chromium/ChromiumBrowserType.cs
=> fix(browserType): fix ChromiumBrowserType overloads

src/PlaywrightSharp/Response.cs
=> fix(network): fix Response.Ok

src/Common/PackageInfo.props, src/PlaywrightSharp/PlaywrightSharp.csproj
=> fix: don't output BuildTasks

src/PlaywrightSharp.Tests/BrowserTypeLaunchTests.cs, src/PlaywrightSharp/LaunchOptions.cs
=> fix(browserType): fix env property serialization

src/PlaywrightSharp/LaunchOptions.cs
=> fix(browserType): fix ignoreDefaultArgs serialization

src/tools/ApiChecker/ScaffoldTest.cs
=> Improving name generation for scaffolded tests

src/PlaywrightSharp.Tests/ElementHandleConvenienceTests.cs, src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/ElementHandleChannel.cs, src/PlaywrightSharp/Transport/Channels/FrameChannel.cs
Support for IsVisibleAsync, IsHiddenAsync, IsEnabledAsync, IsEditableAsync, IsDisabledAsync and IsCheckedAsync
=> chore: API updates

README.md
Fix #1111 
When you copy-paste the Mobile Geolocation snippet provided on README.md file it doesn't wait for map to get loaded. The screenshot generated by the code is mostly depend on the network speed of you machine.
=> Fix Mobile Geolocation snippet

demos/ScreenshotsDemo/Program.cs
=> Make IO bound operation (write image) asynchronous

src/PlaywrightSharp/runtimes/expected_api_mismatch.json
=> codegen: Ignore Android and Electron classes

src/PlaywrightSharp/ElementHandle.cs, src/PlaywrightSharp/Frame.cs, src/PlaywrightSharp/IElementHandle.cs, src/PlaywrightSharp/IFrame.cs, src/PlaywrightSharp/IJSHandle.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/IWorker.cs, src/PlaywrightSharp/JSHandle.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Worker.cs, src/PlaywrightSharp/runtimes/expected_api_mismatch.json
=> codegen: rename pageFunction to expression

src/PlaywrightSharp/PlaywrightSharp.csproj
Help people like myself who failed to read https://github.com/microsoft/playwright-sharp/blob/master/CONTRIBUTING.md#prerequisites with a nicer build failure.
=> chore(build): make build failure friendlier

src/PlaywrightSharp/BrowserContext.cs, src/PlaywrightSharp/IPage.cs, src/PlaywrightSharp/Page.cs, src/PlaywrightSharp/Transport/Channels/BrowserContextChannel.cs
closes #1162 
I didn't implement the tests because they need some interesting tooling that we don't have on our side.
=> feat(page): introduce Page.PauseAsync

.github/workflows/nuget.yml, src/Common/PackageInfo.props
=> chore: fix nuget publish

src/Common/PackageInfo.props, src/PlaywrightSharp/Transport/Connection.cs
=> fix(drivers): fix drivers on linux

.github/workflows/tests.yml, src/Common/PackageInfo.props, src/PlaywrightSharp.Tests/BeforeUnloadTests.cs, src/PlaywrightSharp.Tests/BrowserContextExposeFunctionTests.cs, src/PlaywrightSharp.Tests/BrowserContextPageEventTests.cs, src/PlaywrightSharp.Tests/HarTests.cs, src/PlaywrightSharp.Tests/NetworkPostDataTests.cs, src/PlaywrightSharp.Tests/SelectorsTextTests.cs, src/PlaywrightSharp/Request.cs, src/tools/PlaywrightSharp.Tooling/DriverDownloader.cs
*Includes https://github.com/microsoft/playwright-sharp/commit/8de47d226972bbe11c0d4e276a5e806d8e97c07d
=> release: roll drivers to 1.9.2 

src/PlaywrightSharp/Transport/Connection.cs
To help debug when something goes wrong.
=> Write locations in "Driver not found in any of the locations"

src/Playwright.Tests/ScreencastTests.cs, src/Playwright/Artifact.cs, src/Playwright/Browser.cs, src/Playwright/BrowserContext.cs, src/Playwright/Page.cs, src/Playwright/Transport/Channels/PageChannel.cs, src/Playwright/Transport/Channels/VideoEventArgs.cs, src/Playwright/Transport/Connection.cs, src/Playwright/Transport/Protocol/ArtifactInitializer.cs, src/Playwright/Transport/Protocol/DownloadInitializer.cs, src/Playwright/Video.cs
=> chore(video): use artifacts in videos

src/Playwright.Tests/PopupTests.cs, src/Playwright/BrowserContext.cs, src/Playwright/ContextEvent.cs, src/Playwright/Contracts/IBrowserContext.cs
=> feat(context): introduce WaitForPageAsync

src/Playwright.Tests/BrowserContextExposeFunctionTests.cs
While adding documentation examples, this became an issue, adding it as a test.
=> chore(test): adding expose handle test

src/Playwright.Tests/BrowserContextAddCookiesTests.cs, src/Playwright.Tests/BrowserContextClearCookiesTests.cs, src/Playwright.Tests/BrowserContextCookiesTests.cs, src/Playwright.Tests/DefaultBrowserContext1Tests.cs, src/Playwright.Tests/GeolocationTests.cs, src/Playwright.Tests/HarTests.cs, src/Playwright.Tests/HeadfulTests.cs, src/Playwright.Tests/PageRouteTests.cs, src/Playwright.Tests/PageSelectOptionTests.cs, src/Playwright.Tests/PermissionsTests.cs, src/Playwright/BrowserContext.cs, src/Playwright/Contracts/IBrowserContext.cs, src/Playwright/Contracts/IElementHandle.cs, src/Playwright/Contracts/IFrame.cs, src/Playwright/Contracts/IPage.cs, src/Playwright/ElementHandle.cs, src/Playwright/Frame.cs, src/Playwright/Page.cs
=> chore: remove params overloads

src/Playwright.Tests/DefaultBrowserContext1Tests.cs, src/Playwright.Tests/DefaultBrowsercontext2Tests.cs, src/Playwright.Tests/DownloadTests.cs, src/Playwright.Tests/ProxyTests.cs, src/Playwright.Tests/TestConstants.cs, src/Playwright/Browser.cs, src/Playwright/BrowserType.cs, src/Playwright/Contracts/IBrowser.cs, src/Playwright/Contracts/IBrowserType.cs, src/Playwright/Contracts/Models/BrowserContextOptions.cs, src/Playwright/Contracts/Models/Geolocation.cs, src/Playwright/LaunchOptions.cs, src/Playwright/LaunchOptionsBase.cs, src/Playwright/LaunchPersistentOptions.cs
closes #1358
closes #1332
closes #1331
=> chore: restore launch options

src/Playwright.Tests/BaseTests/PlaywrightSharpBrowserContextBaseTest.cs, src/Playwright.Tests/PageGoToTests.cs, src/Playwright.Tests/PageSetContentTests.cs, src/Playwright.Tests/PageSetInputFilesTests.cs, src/Playwright.Tests/PageWaitForFunctionTests.cs, src/Playwright.Tests/PageWaitForRequestTests.cs, src/Playwright.Tests/PageWaitForResponseTests.cs, src/Playwright/BrowserContext.cs, src/Playwright/Contracts/IBrowserContext.generated.cs, src/Playwright/Contracts/IPage.generated.cs, src/Playwright/Frame.cs, src/Playwright/Page.cs
generated from https://github.com/microsoft/playwright/pull/6531
=> chore: Replace set properties by methods

src/Playwright.Tests/NetworkPostDataTests.cs, src/Playwright.Tests/PageNetworkRequestTest.cs, src/Playwright/Contracts/IRequest.generated.cs, src/Playwright/Request.cs
generated using https://github.com/microsoft/playwright/pull/6533
closes #1361
=> chore: rename getPayloadAsJson to PostDataJsonAsync

src/Playwright.Tests/BrowserContextExposeFunctionTests.cs, src/Playwright.Tests/NetworkPostDataTests.cs, src/Playwright.Tests/PageNetworkRequestTest.cs, src/Playwright/Contracts/IJSHandle.generated.cs, src/Playwright/JSHandle.cs
generated from https://github.com/microsoft/playwright/pull/6576
=> chore: Generate `As` as methods

src/Playwright/Playwright.csproj
Begin a good citizen and adding [a readme file](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/) to the NuGet package.
=> chore(nuget): add README to the NuGet package

src/Playwright/build/netstandard2.0/Microsoft.Playwright.targets
=> chore: copy drivers on publish

README.md
The sample uses Firefox but it was labelled as Webkit.
=> Fix sample typo

src/Playwright.Tests/BrowserContextPageEventTests.cs, src/Playwright.Tests/PageClickTests.cs, src/Playwright.Tests/PageEventCrashTests.cs, src/Playwright.Tests/PageNetworkIdleTests.cs, src/Playwright.Tests/PageWaitForNavigationTests.cs, src/Playwright.Tests/WebSocketTests.cs
this will help users to take tests as examples.
closes #1381
=> tests: remove WithTimeout from tests

src/Playwright.Tests/ElementHandleConvenienceTests.cs, src/Playwright.Tests/ElementHandleScreenshotTests.cs, src/Playwright.Tests/GeolocationTests.cs, src/Playwright.Tests/PageAutoWaitingBasicTests.cs, src/Playwright.Tests/PageBasicTests.cs, src/Playwright.Tests/PageRouteTests.cs, src/Playwright.Tests/PageWaitForRequestTests.cs
=> fix(tests): test code cleanup, redundant variables

src/Playwright.Tests/PageEvaluateTests.cs, src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
=> feat(page): support enum properties in evaluate

src/Playwright.Tests/BrowserContextNetworkEventTests.cs, src/Playwright.Tests/DefaultBrowsercontext2Tests.cs, src/Playwright.Tests/DownloadsPathTests.cs, src/Playwright.Tests/PageEmulateMediaTests.cs, src/Playwright.Tests/TracingTests.cs
- BrowserContextNetworkEvents 
- DownloadPaths
- ReducedMotion
- Tracing
Closes #1477
=> feat: tests for 1.12 features

README.md
=> docs: update readme with recent changes

README.md
Fix for a small typo.
P.S.
*Just discovered your project. Great work!*
=> trivial: typo in README

README.md, src/Playwright.CLI/Playwright.CLI.csproj, src/Playwright.CLI/Program.cs
=> chore: update CLI targeting and add requirements to readme

.gitignore, src/Playwright.Tests/build/Playwright.Tests.targets, src/Playwright/Helpers/Paths.cs, src/Playwright/Playwright.csproj, src/Playwright/Program.cs, src/Playwright/build/Microsoft.Playwright.targets, src/tools/Playwright.Tooling/ApiChecker.cs, src/tools/Playwright.Tooling/DriverDownloader.cs
=> fix: driver discovery and folder consolidation

src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
since the parent if checks that
=> remove redundant ValueKind checks

src/Playwright.Tests/PageEventCrashTests.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/Video.cs
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards
=> discard some params

src/Playwright.Tests.TestServer/SimpleServer.cs
i assume we should pass the cancellation token?
=> pass CancellationToken

.gitignore, src/Playwright.Tests/build/Playwright.Tests.targets, src/Playwright/Helpers/Paths.cs, src/Playwright/Playwright.csproj, src/Playwright/Program.cs, src/Playwright/build/Microsoft.Playwright.targets, src/tools/Playwright.Tooling/ApiChecker.cs, src/tools/Playwright.Tooling/DriverDownloader.cs
* fix: fallback to NuGet repository for driver location
* fix: fixing driver discovery and consolidating driver folders
=> [1.12.3 cherry pick] fix: driver discovery and folder consolidation (#1520)

src/Playwright.NUnit/BrowserTest.cs, src/Playwright.NUnit/PlaywrightTest.cs
=> fix: do not allow unknown browsers to be specified

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
Downstream sync for https://github.com/microsoft/playwright/pull/7477
=> chore: sync with upstream GitHub issue templates

src/Playwright/Core/PlaywrightImpl.cs, src/Playwright/Playwright.csproj, src/Playwright/Transport/Connection.cs, src/Playwright/Transport/StdIOTransport.cs
=> fix(stderr): remove ILogger and ILoggerFactory and re-route stderr

src/Playwright.Tests/BrowserContextRouteTests.cs, src/Playwright.Tests/PageRouteTests.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Page.cs
=> fix(routes): process last inserted routes first in request interception

.gitmodules, build.ps1
This PR introduces the submodule for upstream dependency. The intent here is to help us ensure that we have a "stable" state of the docs from which our API was generated from, etc.
Additionally, it introduces a build task helper that encapsulates a bunch of common commands (like downloading the driver, generating the API, etc.) which are common during the dev process.
=> chore(eng): improve rolling

.github/workflows/integrity-checks.yml
=> chore(eng): introduce API integrity checking

src/Playwright/Transport/Channels/WebSocketChannel.cs
=> fix(websockets): filter for text and binary frames

src/Playwright/Core/Frame.cs, src/Playwright/Core/Waiter.cs
See: https://github.com/microsoft/playwright-dotnet/issues/1664
=> fix: event info for waitForLoadState

src/Playwright.Tests/Attributes/PlaywrightTestAttribute.cs, src/Playwright.Tests/PageWaitForNavigationTests.cs, src/Playwright/Core/BrowserContext.cs
=> fix(timeout): default timeout was being set to 0 instead of null

src/tools/Playwright.Tooling/DriverDownloader.cs
Use the commit hash to lookup the current README.
=> chore: improve driver download readme update

ROLLING.md
=> docs: add info on rolling

src/Playwright/Program.cs
=> fix(cli): fix .NET's escaping of quotes in cli args

.github/workflows/smoke-tests.yml, src/Playwright.MSTest/BrowserTest.cs, src/Playwright.MSTest/ContextTest.cs, src/Playwright.MSTest/PageTest.cs, src/Playwright.MSTest/PlaywrightTest.cs, src/Playwright.TestingHarnessTest/Playwright.TestingHarnessTest.csproj, src/Playwright.TestingHarnessTest/SimpleSmokeTests.MSTest.cs, src/Playwright.TestingHarnessTest/SimpleSmokeTests.NUnit.cs, src/Playwright.TestingHarnessTest/index.html, src/Playwright.sln
=> chore(mstest): fix CI warnings and introduce basic smoke test for mstest

src/Playwright.Tests/PageWaitForNavigationTests.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/Page.cs
=> fix: follow-up fix for waitEventInfo

.github/workflows/nuget-package-tests.yml, src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.48.csproj, src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.50.csproj, src/Playwright/Playwright.csproj
=> fix(net48): copy driver when used from net48 projects

src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright/API/Supplements/ILocator.cs, src/Playwright/Core/Locator.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/1750, https://github.com/microsoft/playwright-dotnet/issues/1745
=> fix(locator): add missing locator tests, fix related bugs

src/Playwright/Program.cs, src/Playwright/build/playwright.ps1
Fixes https://github.com/microsoft/playwright-dotnet/issues/1653
=> chore: refix cli

src/Playwright.Tests/BrowserTypeConnectTests.cs, src/Playwright/Helpers/Paths.cs, src/Playwright/Playwright.csproj, src/tools/Playwright.Tooling/DriverDownloader.cs
https://github.com/microsoft/playwright/issues/8045
=> chore: drop Windows 32 bit drivers and use always 64 bit

src/Common/Version.props, src/Playwright.Tests/Locator/LocatorFrameTests.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/IFrameLocator.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/FrameLocator.cs, src/Playwright/Core/Locator.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/Route.cs, src/Playwright/Transport/Connection.cs
Also fixes an evil bug where ContentType﻿ did not work in Route.fulfill
=> feat(frame-locators): roll and implement FrameLocators

src/Playwright.Tests/HARTests.cs, src/Playwright/Core/Browser.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Core/Page.cs, src/Playwright/Transport/Channels/BrowserContextChannel.cs, src/Playwright/Transport/Connection.cs
=> fix: added support for HAR

src/Playwright/Transport/StdIOTransport.cs
=> fix: leaking driver process

src/Playwright/Program.cs
https://github.com/microsoft/playwright-python/issues/1063
=> chore: show correct driver version when using the CLI

src/Playwright/Scripts/playwright.sh
Backports https://github.com/microsoft/playwright/pull/7240
=> chore: fix in folders which contain spaces

src/Playwright.Tests/BrowserTypeConnectOverCDPTests.cs, src/Playwright/API/Generated/IBrowserType.cs, src/Playwright/API/Generated/IFrameLocator.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/Options/BrowserTypeConnectOverCDPOptions.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Core/LocalUtils.cs, src/Playwright/Transport/Channels/BrowserTypeChannel.cs, src/Playwright/Transport/Protocol/Generated/LocalUtilsInitializer.cs
Not sure which tests are relevant to mirror over.
Fixes https://github.com/microsoft/playwright-dotnet/issues/1291
=> feat: add BrowserType.ConnectOverCDPAsync

src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IElementHandle.cs, src/Playwright/API/Generated/IJSHandle.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Supplements/IJSHandle.cs, src/Playwright/Core/JSHandle.cs, src/Playwright/Core/Locator.cs
Requires https://github.com/microsoft/playwright/pull/10905
Fixes https://github.com/microsoft/playwright-dotnet/issues/1785
=> chore: make JSHandle inherit from IAsyncDisposable

src/Playwright.CLI/Playwright.CLI.csproj
https://github.com/microsoft/playwright-dotnet/pull/1885
=> cherry-pick(release-1.17): chore: fix CLI on .NET 6 (#1885)

src/Playwright.CLI/Playwright.CLI.csproj
=> build: add RollForward to cli csproj

src/Playwright.CLI/Playwright.CLI.csproj
=> cherry-pick(release-1.17): build: add RollForward to cli csproj (#1792)

src/Playwright.CLI/Playwright.CLI.csproj
This reverts commit 6e2de066e2f02707d44c24bd014931b660706a28.
Fixes #1893
=> Revert "chore: fix CLI on .NET 6 (#1885)"

src/Playwright.CLI/Playwright.CLI.csproj
This reverts commit 6e2de066e2f02707d44c24bd014931b660706a28.
=> cherry-pick(release-1.17): Revert "chore: fix CLI on .NET 6 (#1885)" (#1896)

src/tools/Playwright.Tooling/DriverDownloader.cs
This does not change any user-behaviour, only internal tooling.
Azure CDN (Azure App Service HTTP requests to Azure VNet IP Addresses) fail after upgrading to .NET 5.0. This is because they don't support dual-socket TCP connections which are default in .NET 6+.
Relates https://github.com/dotnet/runtime/issues/44686#issuecomment-733797994
=> chore: fix driver download by not using dual-socket TCP connections

src/Playwright/Transport/Connection.cs
Nobody was adding anything to `_waitingForObject`. Only trying to remove from it. Might be a left over?
The same is true for js:
https://github.com/microsoft/playwright/blob/976af162b07eb9b056f83f4c0439f10d0d4aba5c/packages/playwright-core/src/client/connection.ts#L59
https://github.com/microsoft/playwright/blob/976af162b07eb9b056f83f4c0439f10d0d4aba5c/packages/playwright-core/src/client/connection.ts#L266-L270
=> remove unused _waitingForObject from Connection

src/Common/Version.props
This version will be released as stable.
=> chore: roll to latest version of beta driver

src/Playwright/Core/Request.cs, src/Playwright/Transport/Protocol/Generated/RequestInitializer.cs
follow up to https://github.com/microsoft/playwright/pull/11539
=> change RequestInitializer PostData to byte[]

src/Playwright.Tests/TracingTests.cs, src/Playwright/Core/Tracing.cs
=> fix: save trace without path

src/Playwright.Tests/BrowserContextRouteTests.cs, src/Playwright.Tests/PageRouteTests.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/Route.cs, src/Playwright/Core/RouteSetting.cs
=> fix: network routes with times option

src/Playwright.Tests/ProxyTests.cs
PR: #1958
Co-authored-by: Max Schmitt <max@schmitt.mx>
=> cherry-pick(release-1.18): test: fix ProxyTests to not use foo.zone as it is now a site that actually exists

src/Playwright.Tests/CLITests.cs
=> test: add test for CLI command

src/Playwright.Tests/CLITests.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/Route.cs, src/Playwright/Transport/Channels/BindingCallEventArgs.cs, src/Playwright/Transport/Channels/BrowserContextChannel.cs, src/Playwright/Transport/Channels/PageChannel.cs
=> chore: follow up on ignoring task exceptions

src/Playwright.Tests/CLITests.cs
=> test: hide stdout/stderr inside CLI tests

README.md, src/Common/Version.props, src/Playwright.Tests/CLITests.cs, src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright/API/Generated/Options/FrameLocatorLocatorOptions.cs, src/Playwright/API/Generated/Options/FrameLocatorOptions.cs, src/Playwright/API/Generated/Options/LocatorLocatorOptions.cs, src/Playwright/API/Generated/Options/PageLocatorOptions.cs, src/Playwright/API/Generated/Options/TracingStartOptions.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/Locator.cs, src/Playwright/Core/Page.cs
=> chore: roll Playwright to 1.19.0

src/Playwright/build/Microsoft.Playwright.targets
=> cherry-pick(1.19): chore: don't include PlaywrightCopyItems in pack

src/Playwright.MSTest/PlaywrightTest.cs, src/Playwright.NUnit/PlaywrightTest.cs, src/Playwright.TestingHarnessTest/SimpleSmokeTests.MSTest.cs, src/Playwright.TestingHarnessTest/SimpleSmokeTests.NUnit.cs, src/Playwright.Tests/Assertions/LocatorAssertionsTests.cs, src/Playwright.Tests/Assertions/PageAssertionsTests.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2042
=> chore: use Expect as a method on the testing harness rather than use static

Directory.Build.props, src/Playwright.CLI/Playwright.CLI.csproj, src/Playwright.MSTest/Playwright.MSTest.csproj, src/Playwright.NUnit/Playwright.NUnit.csproj, src/Playwright/Playwright.csproj
fixes #2050 
for the full context on this approach: https://github.com/dotnet/sdk/issues/2679
=> move to DebugType>embedded

.github/workflows/test_docker.yml, .github/workflows/tests.yml, utils/docker/Dockerfile.focal
The Docker pipeline was broken. This fixes it.
=> devops: various fixes and enhancements

README.md, src/.editorconfig, src/Common/Version.props, src/Playwright.Tests.TestServer/SimpleServer.cs, src/Playwright.Tests/BrowserTypeConnectOverCDPTests.cs, src/Playwright.Tests/BrowserTypeConnectTests.cs, src/Playwright.Tests/Locator/LocatorMiscTests.cs, src/Playwright.Tests/Playwright.Tests.csproj, src/Playwright/API/Generated/Enums/ScreenshotAnimations.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/ILocatorAssertions.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IPageAssertions.cs, src/Playwright/API/Generated/IPlaywrightAssertions.cs, src/Playwright/API/Generated/Options/ElementHandleScreenshotOptions.cs, src/Playwright/API/Generated/Options/LocatorScreenshotOptions.cs, src/Playwright/API/Generated/Options/PageScreenshotOptions.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Core/ElementHandle.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/Locator.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/SocksSupport.cs, src/Playwright/Transport/Channels/BrowserTypeChannel.cs, src/Playwright/Transport/Channels/ChannelOwnerType.cs, src/Playwright/Transport/Channels/ElementHandleChannel.cs, src/Playwright/Transport/Channels/FrameChannel.cs, src/Playwright/Transport/Channels/PageChannel.cs, src/Playwright/Transport/Connection.cs, src/Playwright/Transport/Protocol/Generated/SocksSupportInitializer.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2011
Masks tests are not there, we don't have any screenshot comparison functionality yet, will check it before merging manually for now.
=> chore: roll to Playwright 1.20.0-beta-1646791472000

src/Playwright/Transport/Connection.cs
Fixes [#2074](https://github.com/microsoft/playwright-dotnet/issues/2074)
=> Fixes issue: NullReferenceException in Connection.WrapApiCallAsync #2074

src/Playwright/Transport/Connection.cs
=> cherry-pick(#2075): fixes: NullReferenceException in Connection.WrapApiCallAsync

.github/workflows/smoke-tests.yml, .github/workflows/test_docker.yml, .github/workflows/tests.yml, src/Common/Version.props, src/Playwright.Tests.TestServer/SimpleServer.cs, src/Playwright.Tests.TestServer/assets/input/fileupload.html, src/Playwright.Tests/BrowserTypeConnectTests.cs, src/Playwright.Tests/PageSetInputFilesTests.cs, src/Playwright/Core/ElementHandle.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/WritableStream.cs, src/Playwright/Helpers/SetInputFilesHelpers.cs, src/Playwright/Helpers/StringExtensions.cs, src/Playwright/Transport/Channels/BrowserContextChannel.cs, src/Playwright/Transport/Channels/ChannelOwnerType.cs, src/Playwright/Transport/Channels/ElementHandleChannel.cs, src/Playwright/Transport/Channels/FrameChannel.cs, src/Playwright/Transport/Channels/WritableStreamChannel.cs, src/Playwright/Transport/Connection.cs, src/Playwright/Transport/Converters/ChannelOwnerListToGuidListConverter.cs, src/Playwright/Transport/Protocol/InputFilesList.cs, src/Playwright/Transport/Protocol/SetInputFilesFiles.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2064
=> chore: allow file uploads by file path

README.md, src/Common/Version.props, src/Playwright.Tests/ElementHandleScrollIntoViewTests.cs, src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright/API/Generated/IBrowser.cs, src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IElementHandle.cs, src/Playwright/API/Generated/IFileChooser.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/ILocatorAssertions.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IPageAssertions.cs, src/Playwright/API/Generated/IPlaywrightAssertions.cs, src/Playwright/API/Generated/Options/LocatorThatOptions.cs, src/Playwright/Core/Locator.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2096
=> chore(roll): roll Playwright to 1.22.0-alpha-apr-27-2022

src/Playwright/Program.cs
Reverting the impl of https://github.com/microsoft/playwright-dotnet/pull/2072 for now until https://github.com/dotnet/runtime/issues/68259 is fixed. 
Also we have now a progress bar for != isTTY mode, so we are good by that. https://github.com/microsoft/playwright/pull/13690
Fixes https://github.com/microsoft/playwright-dotnet/issues/2103
=> chore: restore old manual stdout/stderr redirection of CLI

src/Playwright.Tests/BrowserTypeConnectOverCDPTests.cs
Port upstream test for https://github.com/microsoft/playwright-dotnet/issues/2152.
=> test: add test for connectOverCDP get all pages

.github/workflows/test_docker.yml, .github/workflows/trigger_internal_tests.yml, src/Playwright/Helpers/Driver.cs, src/Playwright/Playwright.csproj, src/Playwright/build/Microsoft.Playwright.targets, src/tools/Playwright.Tooling/DriverDownloader.cs, utils/docker/build.sh
Fixes https://github.com/microsoft/playwright-dotnet/issues/2053
=> chore: support linux arm64

src/Common/Version.props, src/Playwright.Tests/BrowserContextHarTests.cs, src/Playwright/API/Generated/Options/BrowserContextRouteFromHAROptions.cs, src/Playwright/API/Generated/Options/PageRouteFromHAROptions.cs, src/Playwright/Core/Browser.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Core/HarRouter.cs, src/Playwright/Core/LocalUtils.cs, src/Playwright/Core/Page.cs, src/Playwright/Transport/Channels/BrowserChannel.cs, src/Playwright/Transport/Channels/BrowserContextChannel.cs, src/Playwright/Transport/Channels/BrowserTypeChannel.cs, src/Playwright/Transport/Channels/LocalUtilsChannel.cs
https://github.com/microsoft/playwright/commit/6a8d835145e2f4002ee00b67a80a1f70af956703
Fixes https://github.com/microsoft/playwright-dotnet/issues/2189
=> feat: add har update

src/Playwright.Tests/TracingTests.cs, src/Playwright/Core/Route.cs, src/Playwright/Core/Tracing.cs, src/Playwright/Transport/ApiZone.cs, src/Playwright/Transport/Connection.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2185
=> fix: apiName calculation when route is used

src/Playwright.TestingHarnessTest/Playwright.TestingHarnessTest.csproj, src/Playwright.TestingHarnessTest/SimpleSmokeTests.MSTest.cs, src/Playwright.Tests/Playwright.Tests.csproj, src/tools/Playwright.Tooling/Playwright.Tooling.csproj
This bumps dependencies used inside our tests.
=> chore: bump dev dependencies

src/Common/Dependencies.props, src/Playwright.Tests/Playwright.Tests.csproj, src/Playwright/Playwright.csproj, src/tools/Playwright.Tooling/Playwright.Tooling.csproj
This bumps linters which are dev dependencies.
=> chore: bump more dev dependencies

.github/workflows/smoke-tests.yml, .gitignore, src/Playwright.MSTest/ContextTest.cs, src/Playwright.MSTest/PlaywrightTest.cs, src/Playwright.MSTest/Services/BrowserService.cs, src/Playwright.NUnit/BrowserService.cs, src/Playwright.NUnit/PlaywrightTest.cs, src/Playwright.NUnit/SkipAttribute.cs, src/Playwright.NUnit/WorkerAwareTest.cs, src/Playwright.TestingHarnessTest/.runsettings, src/Playwright.TestingHarnessTest/SimpleSmokeTests.MSTest.cs, src/Playwright.TestingHarnessTest/SimpleSmokeTests.NUnit.cs, src/Playwright.Tests/BaseTests/BrowserTestEx.cs, src/Playwright.Tests/BaseTests/ContextTestEx.cs, src/Playwright.Tests/BaseTests/PageTestEx.cs, src/Playwright.Tests/BaseTests/PlaywrightTestEx.cs, src/Playwright.Tests/BrowserContextAddCookiesTests.cs, src/Playwright.Tests/PageGotoTests.cs, src/Playwright.Tests/TestConstants.cs, src/Playwright/Core/Shared/RunSettingsParser.cs
Relates https://github.com/microsoft/playwright-dotnet/issues/1730 we'll follow-up with docs to close it.
=> chore: consider runsettings TestRunParameters in context/browser creation

utils/docker/Dockerfile.focal
https://github.com/microsoft/playwright-dotnet/issues/2223
=> chore: add 'gpg' to Dockerfile

src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright/Core/Locator.cs
https://github.com/microsoft/playwright-python/issues/1434
=> chore: do not encode Locators with has/hasText

README.md, src/Common/Version.props, src/Playwright.Tests/ElementHandleScrollIntoViewTests.cs, src/Playwright/API/Generated/IPlaywrightAssertions.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Transport/ChannelOwnerBase.cs, src/Playwright/Transport/Channels/IChannelOwner.cs, src/Playwright/Transport/Connection.cs, src/Playwright/Transport/Protocol/Generated/BrowserContextInitializer.cs
https://github.com/microsoft/playwright-dotnet/issues/2196
=> chore(roll): roll Playwright to 1.25.0-alpha-jul-28-2022

src/Playwright.MSTest/PlaywrightTest.cs, src/Playwright.NUnit/WorkerAwareTest.cs, src/Playwright.TestingHarnessTest/tests/mstest.spec.ts, src/Playwright.TestingHarnessTest/tests/nunit.spec.ts, src/Playwright/Core/AssertionsBase.cs, src/Playwright/Core/Shared/RunSettingsParser.cs, src/Playwright/Playwright.csproj, src/tools/Playwright.Tooling/Playwright.Tooling.csproj
Fixes https://github.com/microsoft/playwright-dotnet/issues/2237
=> chore: add runsettings option to set the expect-timeout

src/Playwright/Helpers/Driver.cs
Context https://github.com/microsoft/playwright-dotnet/pull/2266#discussion_r952426589
=> chore: respect CodeBase follow-up

CONTRIBUTING.md, src/Playwright.MSTest/PlaywrightTest.cs, src/Playwright.NUnit/PlaywrightTest.cs, src/Playwright.Tests/Assertions/APIResponseAssertionsTests.cs, src/Playwright/API/Generated/IAPIResponseAssertions.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IPlaywrightAssertions.cs, src/Playwright/Assertions.cs, src/Playwright/Core/APIResponse.cs, src/Playwright/Core/APIResponseAssertions.cs, src/Playwright/Transport/Channels/APIRequestContextChannel.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2249
=> feat: add api response assertions

src/Playwright/Transport/StdIOTransport.cs
- Use `ArraySegment` instead of `ToArray`
- Keep track of the offset to only resize the List once after all current messages have been read
- Use `List.CopyTo` instead of `GetRange` / `ToArray`
Remove some `#pragma warning`s since `netstandard2.0` is the only target.
=> chore: reduce array allocations / resizes in StdIOTransport

src/Playwright.Tests/TracingTests.cs, src/Playwright/Core/Tracing.cs
=> fix: TracingStopChunkOptions can be null

src/Playwright/Transport/Connection.cs
The same object got tryadded 3 times before:
- `OnObjectCreated` which wasn't really used.
- `CreateRemoteObject`
- `ChannelOwnerBase`
Now only `ChannelOwnerBase` adds objects which aligns with upstream / java.
---
`__adopt__` was wrong as it adopted the object itself, now it adopts the child correctly.
---
Throw exception when callback is not found.
---
Remove some #pragma warnings since netstandard2.0 is the only target.
=> chore: cleanup connection and align with upstream

src/Playwright.Tests/BaseTests/PlaywrightAssert.cs, src/Playwright.Tests/PageBasicTests.cs, src/Playwright.Tests/PageDragTests.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/Page.cs, src/Playwright/Transport/Channels/FrameChannel.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2298
=> fix: source/target position was not passed for drag'n drop

README.md, src/Common/Version.props, src/Playwright.Tests/Assertions/LocatorAssertionsTests.cs, src/Playwright.Tests/GlobalFetchTests.cs, src/Playwright/API/Generated/IBrowserType.cs, src/Playwright/API/Generated/ILocatorAssertions.cs, src/Playwright/API/Generated/IPageAssertions.cs, src/Playwright/API/Generated/IPlaywrightAssertions.cs, src/Playwright/API/Generated/Options/APIRequestContextOptions.cs, src/Playwright/API/Generated/Options/LocatorAssertionsToBeEditableOptions.cs, src/Playwright/API/Generated/Options/LocatorAssertionsToBeEnabledOptions.cs, src/Playwright/API/Generated/Options/LocatorAssertionsToBeVisibleOptions.cs, src/Playwright/Core/APIRequestContext.cs, src/Playwright/Core/LocatorAssertions.cs, src/Playwright/Transport/Channels/APIRequestContextChannel.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2294
=> chore(roll): roll Playwright to 1.26.0-beta-1662762342000

src/Playwright.Tests/ElementHandleConvenienceTests.cs, src/Playwright.Tests/Locator/LocatorConvenienceTests.cs, src/Playwright.Tests/Locator/LocatorElementHandleTests.cs, src/Playwright.Tests/Locator/LocatorEvaluateTests.cs, src/Playwright.Tests/Locator/LocatorFrameTests.cs, src/Playwright.Tests/Locator/LocatorHighlightTests.cs, src/Playwright.Tests/Locator/LocatorIsVisibleTests.cs, src/Playwright.Tests/Locator/LocatorMisc1Tests.cs, src/Playwright.Tests/Locator/LocatorMisc2Tests.cs, src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright.Tests/SelectorsRegisterTests.cs, src/Playwright.Tests/TaskUtils.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/Locator.cs, src/Playwright/Transport/Channels/FrameChannel.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2299
=> chore: align Locators with upstream impl

src/Common/Version.props, src/Playwright/API/Generated/Enums/AriaRole.cs
this fixes the codegen as well.
fixes https://github.com/microsoft/playwright/issues/18366
=> chore(roll): roll Playwright to 1.27.1-beta-1665679529000

build.sh, src/Playwright/Scripts/playwright.cmd, src/Playwright/Scripts/playwright.sh
Fixes https://github.com/microsoft/playwright-dotnet/issues/2372
=> chore: auto update run-driver scripts

src/Playwright.Tests/PageEvaluateTests.cs, src/Playwright/Helpers/Driver.cs, src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
=> fix: make evaluate work with serializing Guids

src/Playwright/Playwright.csproj
Fixes https://github.com/microsoft/playwright-dotnet/issues/2408.
=> chore: bump deps for .NET 7

.github/workflows/code-style.yml, src/Playwright/Core/CDPSession.cs
Lack of ConfigureAwait is causing an error that prevents generating a new package
=> chore: Configure awaits in CDPSession

src/Playwright.TestAdapter/PlaywrightSettingsXml.cs, src/Playwright.TestingHarnessTest/package-lock.json, src/Playwright.TestingHarnessTest/package.json, src/Playwright.TestingHarnessTest/tests/mstest/basic.spec.ts, src/Playwright.TestingHarnessTest/tests/nunit/basic.spec.ts
Fixes https://github.com/microsoft/playwright-dotnet/issues/2494
=> chore: fix LaunchOptions proxy parsing

src/Playwright/Helpers/Driver.cs, src/Playwright/Playwright.csproj, src/Playwright/build/Microsoft.Playwright.targets, src/tools/Playwright.Tooling/DriverDownloader.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2498
This increases the nuget size by 19%.
=> chore: add support for osx-arm64

src/Playwright.Tests/GlobalFetchTests.cs, src/Playwright/Core/APIRequestContext.cs, src/Playwright/Core/AssertionsBase.cs, src/Playwright/Helpers/ChannelHelpers.cs, src/Playwright/Helpers/ClassUtils.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2510
=> chore: ensure not modifying request options in fetch api

README.md, src/Common/Version.props, src/Playwright.Tests/BrowserContextHarTests.cs, src/Playwright.Tests/BrowserTypeConnectTests.cs, src/Playwright.Tests/FrameGoToTests.cs, src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright.Tests/TracingTests.cs, src/Playwright/API/Generated/Enums/RouteFromHarUpdateContentPolicy.cs, src/Playwright/API/Generated/IBrowser.cs, src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IBrowserType.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/IFrameLocator.cs, src/Playwright/API/Generated/IKeyboard.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/Options/BrowserContextRouteFromHAROptions.cs, src/Playwright/API/Generated/Options/PageRouteFromHAROptions.cs, src/Playwright/Core/Browser.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Core/LocalUtils.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/Tracing.cs, src/Playwright/Transport/Channels/LocalUtilsChannel.cs, src/Playwright/Transport/Channels/TracingChannel.cs, src/Playwright/Transport/Connection.cs
https://github.com/microsoft/playwright-dotnet/issues/2486
=> chore(roll): roll Playwright to 1.32.0-beta-1679448099000

src/Playwright.Tests/GlobalFetchTests.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Helpers/JsonExtensions.cs, src/Playwright/Playwright.cs, src/Playwright/Transport/Channels/APIRequestContextChannel.cs, src/Playwright/Transport/Connection.cs
https://github.com/microsoft/playwright-dotnet/issues/2509
=> fix: send null over the wire for fetch requests

src/Playwright.Tests/PageWaitForRequestTests.cs, src/Playwright.Tests/PageWaitForResponseTests.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2543
=> test: consistent naming of local variables in related unit tests

src/Common/SignFiles.props, src/Playwright.CLI/Playwright.CLI.csproj, src/Playwright.MSTest/Playwright.MSTest.csproj, src/Playwright.NUnit/Playwright.NUnit.csproj, src/Playwright.TestAdapter/Playwright.TestAdapter.csproj, src/Playwright/Playwright.csproj
Fixes https://github.com/microsoft/playwright-dotnet/issues/2569
~To be validated by the user if thats enough for them.~
Reference: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/650/MicroBuild-Signing?anchor=modify-your-project-file-to-include-%60filestosign%60-itemgroup
=> chore: sign Assembly files

src/Playwright.Tests/BrowserContextRouteTests.cs, src/Playwright.Tests/PageRouteTests.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2565
=> test: add test for regex based unroute

src/Playwright.TestAdapter/PlaywrightSettingsXml.cs, src/Playwright.TestingHarnessTest/tests/mstest/basic.spec.ts, src/Playwright.TestingHarnessTest/tests/nunit/basic.spec.ts
Fixes https://github.com/microsoft/playwright-dotnet/issues/2598
=> chore: fix parsing of LaunchOptions.Args

src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Page.cs, src/Playwright/Transport/StdIOTransport.cs
Fixes: https://github.com/microsoft/playwright-dotnet/issues/2590
=> chore: small refinements, Capture Task to fix future compile error

src/Playwright.Tests/Assertions/LocatorAssertionsTests.cs, src/Playwright/Transport/Protocol/Generated/AXNode.cs, src/Playwright/Transport/Protocol/Generated/AndroidSelector.cs, src/Playwright/Transport/Protocol/Generated/ExpectedTextValue.cs, src/Playwright/Transport/Protocol/Generated/Metadata.cs, src/Playwright/Transport/Protocol/Generated/SerializedValue.cs, src/Playwright/Transport/Protocol/Generated/SetNetworkCookie.cs
Fixes https://github.com/microsoft/playwright-dotnet/pull/2583
Fixes https://github.com/microsoft/playwright-dotnet/issues/2581
=> fix: ToHaveAttribute with ignoreCase should work

README.md, src/Common/Version.props, src/Playwright.Tests/BrowserContextCSPTests.cs, src/Playwright.Tests/BrowserContextRouteTests.cs, src/Playwright.Tests/InterceptionTests.cs, src/Playwright.Tests/PageEvaluateTests.cs, src/Playwright.Tests/PageGotoTests.cs, src/Playwright.Tests/PageRouteTests.cs, src/Playwright.Tests/TestUtils.cs, src/Playwright/API/Generated/IAPIRequestContext.cs, src/Playwright/API/Generated/IBrowserType.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/IFrameLocator.cs, src/Playwright/API/Generated/IJSHandle.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/ILocatorAssertions.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IRoute.cs, src/Playwright/API/Generated/ITracing.cs, src/Playwright/Helpers/StringExtensions.cs, src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs, src/Playwright/Transport/Protocol/Generated/SerializedValue.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2621
=> chore(roll): roll Playwright to v1.36.0

src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
This fixes https://github.com/microsoft/playwright-browsers/actions/runs/5554767815/jobs/10144990687
=> chore: use CultureInfo.InvariantCulture for BigInts

README.md, src/Common/Version.props, src/Playwright.Tests/BrowserContextFetchTests.cs, src/Playwright.Tests/FrameGoToTests.cs, src/Playwright.Tests/InterceptionTests.cs, src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/Options/BrowserNewContextOptions.cs, src/Playwright/API/Generated/Options/BrowserNewPageOptions.cs, src/Playwright/API/Generated/Options/BrowserTypeConnectOptions.cs, src/Playwright/API/Generated/Options/BrowserTypeLaunchPersistentContextOptions.cs, src/Playwright/Core/BrowserType.cs, src/Playwright/Core/LocalUtils.cs, src/Playwright/Core/Locator.cs, src/Playwright/Helpers/StringExtensions.cs, src/Playwright/Transport/Channels/LocalUtilsChannel.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2640
=> chore(roll): roll Playwright to 1.37.0-alpha-aug-8-2023

src/Playwright/Transport/StdIOTransport.cs
This PR cherry-picks #2665 / 657f415d3eaa05df2d3dbff0a56526aad285d6f1
=> chery-pick(#2665): fix: Playwright.CreateAsync() without console

.gitignore, README.md, src/Common/Version.props, src/Playwright.Tests/Locator/LocatorMisc2Tests.cs, src/Playwright.Tests/PageEventPopupTests.cs, src/Playwright.Tests/PageNetworkRequestTest.cs, src/Playwright.Tests/PageRequestInterceptTests.cs, src/Playwright.Tests/ScreencastTests.cs, src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IDownload.cs, src/Playwright/API/Generated/IElementHandle.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IPageError.cs, src/Playwright/API/Generated/IRequest.cs, src/Playwright/API/Generated/Options/LocatorPressSequentiallyOptions.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Locator.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/PageError.cs, src/Playwright/Core/Request.cs, src/Playwright/Core/Route.cs, src/Playwright/Transport/Channels/BrowserChannel.cs, src/Playwright/Transport/Channels/BrowserContextChannel.cs, src/Playwright/Transport/Channels/BrowserTypeChannel.cs, src/Playwright/Transport/Channels/PageChannel.cs, src/Playwright/Transport/Protocol/Generated/SerializedValue.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2670
=> feat(roll): roll to Playwright 1.38.0-alpha-sep-4-2023

utils/docker/Dockerfile.focal, utils/docker/Dockerfile.jammy
https://github.com/microsoft/playwright-dotnet/issues/2694#issuecomment-1712741094
This saves us 600 MB.
=> fix: clear nuget cache in Docker image before publishing

README.md, src/Common/Version.props, src/Playwright.Tests/BrowserContextEventsTests.cs, src/Playwright.Tests/PageEvaluateTests.cs, src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IElementHandle.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/IKeyboard.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IWebError.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/WebError.cs, src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
https://github.com/microsoft/playwright-dotnet/issues/2690
=> feat(roll): roll to Playwright 1.38.0

src/Playwright.Tests/PageEvaluateTests.cs, src/Playwright/Helpers/StringExtensions.cs, src/Playwright/Transport/Channels/TracingChannel.cs, src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
See https://github.com/dotnet/runtime/issues/65396
=> chore: use static JsonSerializerOptions

src/Playwright.Tests/Locator/LocatorQueryTests.cs, src/Playwright.Tests/SelectorsGetByTests.cs, src/Playwright.Tests/SelectorsTextTests.cs, src/Playwright/Core/Locator.cs
https://github.com/microsoft/playwright-dotnet/issues/2690
in particular:
=> chore: roll to new RegExp/string escaping

src/Playwright.MSTest/ContextTest.cs, src/Playwright.NUnit/ContextTest.cs, src/Playwright.Tests.TestServer/SimpleServer.cs, src/Playwright.Tests/FrameGoToTests.cs, src/Playwright.Tests/GlobalFetchTests.cs, src/Playwright.Tests/PageEventNetworkTests.cs, src/Playwright.Tests/PageGotoTests.cs, src/Playwright.Tests/PageNetworkRequestTest.cs, src/Playwright.Tests/PageRequestFulfillTests.cs, src/Playwright.Tests/PageRequestInterceptTests.cs
https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0016?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0019?view=aspnetcore-8.0
=> chore: address .NET 8 linter warnings

src/Playwright/Core/APIRequestContext.cs
=> chore: rename isJsonParsable to IsJsonParsable

src/Playwright/build/Microsoft.Playwright.targets
Should work for build and publish.
Fixes #2770
=> chore: chmod playwright.sh

src/Playwright/Core/Page.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2811
=> fix(page): RouteFromHarAsync embed files

src/Playwright.Tests/BrowserContextFetchTests.cs, src/Playwright/API/Supplements/IAPIResponse.cs, src/Playwright/Core/APIResponse.cs, src/Playwright/Playwright.csproj
Allow for easier deserializing, fixes #2817 
Build fails when getting dependencies - didn't change anything at this level however
=> add JsonSerializerOptions to JsonAsync (#2817)

src/Playwright.Tests/BrowserContextBasicTests.cs
Backporting https://github.com/microsoft/playwright/issues/28558
=> test: unflake ShouldWorkWithOfflineOption

src/Playwright/Core/BrowserType.cs
Fixes https://github.com/microsoft/playwright-dotnet/pull/2794#issuecomment-1895677252
=> fix(launch): protocol option mismatch

README.md, src/Common/Version.props, src/Playwright.TestingHarnessTest/tests/mstest/basic.spec.ts, src/Playwright.TestingHarnessTest/tests/nunit/basic.spec.ts, src/Playwright.Tests.TestServer/SimpleServer.cs, src/Playwright.Tests.TestServer/assets/headings.html, src/Playwright.Tests.TestServer/assets/input/handle-locator.html, src/Playwright.Tests/BrowserContextHarTests.cs, src/Playwright.Tests/BrowserContextStorageStateTests.cs, src/Playwright.Tests/ElementHandleScrollIntoViewTests.cs, src/Playwright.Tests/PageAddLocatorHandlerTests.cs, src/Playwright.Tests/PageClickTimeout1Tests.cs, src/Playwright.Tests/PageClickTimeout2Tests.cs, src/Playwright.Tests/PageClickTimeout4Tests.cs, src/Playwright.Tests/PdfTests.cs, src/Playwright/API/Generated/IBrowserContext.cs, src/Playwright/API/Generated/IElementHandle.cs, src/Playwright/API/Generated/IFrame.cs, src/Playwright/API/Generated/IKeyboard.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IRoute.cs, src/Playwright/API/Generated/Options/PagePdfOptions.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/HarRouter.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/ScriptsHelper.cs, src/Playwright/Core/Selectors.cs, src/Playwright/Helpers/Driver.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/2772
Fixes https://github.com/microsoft/playwright-dotnet/pull/2844
Fixes https://github.com/microsoft/playwright-dotnet/issues/2819
=> chore(roll): roll Playwright to 1.42.0-alpha-2024-02-19

src/Playwright/Playwright.csproj
Fixes https://github.com/microsoft/playwright-dotnet/issues/2874
cc @nohwnd - looks like a low-risk change I guess.
=> chore: set <NoWin32Manifest>true</NoWin32Manifest>

src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/FormData.cs, src/Playwright/Core/Frame.cs, src/Playwright/Core/Page.cs, src/Playwright/Helpers/SetInputFilesHelpers.cs, src/Playwright/Helpers/StringExtensions.cs, src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
Extracted from https://github.com/microsoft/playwright-dotnet/pull/2893
=> chore: address some net8.0 warnings

src/Playwright/build/Microsoft.Playwright.targets
Fixes https://github.com/microsoft/playwright-dotnet/issues/2899
Tested.
=> fix(pack): allow packing win runtime on posix systems

.github/workflows/publish_docker.yml
https://github.com/microsoft/playwright-internal/issues/203
=> devops: migrate to OIDC for Docker publishing

.azure-pipelines/publish.yml
As per https://portal.microsofticm.com/imp/v3/incidents/incident/467483180/summary.
Fixes https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9386261&view=logs&s=5f728f2c-8e90-5f89-7c9f-df1bf8cf5b7b
=> devops: fix publishing pipeline

src/Playwright.CLI/Playwright.CLI.csproj, src/Playwright.MSTest/Playwright.MSTest.csproj, src/Playwright.NUnit/Playwright.NUnit.csproj, src/Playwright.TestAdapter/Playwright.TestAdapter.csproj, src/Playwright/Playwright.csproj
See https://github.com/actions/checkout/issues/1689#issuecomment-2075613587
Fixes https://github.com/microsoft/playwright-browsers/actions/runs/8968516761/job/24628087275
Seems to work as per https://github.com/microsoft/playwright-browsers/actions/runs/8968704597/job/24628674225
=> chore: bump Microsoft.SourceLink.GitHub to v8.0.0

utils/docker/publish_docker.sh
Fixes https://github.com/microsoft/playwright-dotnet/actions/runs/10835808270/job/30068126341#step:9:8355
Relates https://github.com/microsoft/playwright-dotnet/issues/3011
=> devops: fix Docker publishing

README.md, src/Common/Version.props, src/Playwright.Tests/PageAriaSnapshotTests.cs, src/Playwright.Tests/PageRouteWebSocketTests.cs, src/Playwright.Tests/TracingTests.cs, src/Playwright/API/Generated/IClock.cs, src/Playwright/API/Generated/IKeyboard.cs, src/Playwright/API/Generated/ILocator.cs, src/Playwright/API/Generated/ILocatorAssertions.cs, src/Playwright/API/Generated/IPage.cs, src/Playwright/API/Generated/IRoute.cs, src/Playwright/API/Generated/ITracing.cs, src/Playwright/API/Generated/IWebSocketRoute.cs, src/Playwright/API/Generated/Options/BrowserNewContextOptions.cs, src/Playwright/API/Generated/Options/BrowserNewPageOptions.cs, src/Playwright/API/Generated/Options/BrowserTypeLaunchPersistentContextOptions.cs, src/Playwright/API/Generated/Options/LocatorAriaSnapshotOptions.cs, src/Playwright/API/Generated/Options/LocatorAssertionsToMatchAriaSnapshotOptions.cs, src/Playwright/API/Generated/Options/PageEmulateMediaOptions.cs, src/Playwright/API/Generated/Options/TracingGroupOptions.cs, src/Playwright/API/Generated/Types/Location.cs, src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Locator.cs, src/Playwright/Core/LocatorAssertions.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/RouteHandler.cs, src/Playwright/Core/Tracing.cs, src/Playwright/Core/WebSocketRouteHandler.cs, src/Playwright/Helpers/URLMatch.cs
Fixes https://github.com/microsoft/playwright-dotnet/issues/3014
=> chore(roll): roll Playwright to v1.49.0

src/Playwright/Core/BrowserContext.cs, src/Playwright/Core/Page.cs, src/Playwright/Core/RouteHandler.cs, src/Playwright/Core/WebSocketRouteHandler.cs, src/Playwright/Helpers/URLMatch.cs
This addresses https://github.com/microsoft/playwright-dotnet/pull/3056#discussion_r1848533844 in order to further align this language port with upstream.
There should be no user-facing changes.
=> chore align route handling with upstream

src/Playwright.TestingHarnessTest/package-lock.json, src/Playwright.TestingHarnessTest/package.json, src/Playwright.TestingHarnessTest/tests/baseTest.ts, src/Playwright.TestingHarnessTest/tests/mstest/basic.spec.ts, src/Playwright.TestingHarnessTest/tests/nunit/basic.spec.ts, src/Playwright.TestingHarnessTest/tests/xunit/basic.spec.ts, src/Playwright.TestingHarnessTest/tsconfig.json
Motivation: The dependency triggered a deprecation warning and we don't need this dependency.
=> test: remove http-proxy package

src/Playwright.Tests/TestServer/SimpleServer.cs
[Mirrors js TestServer](https://github.com/microsoft/playwright/blob/main/tests/config/testserver/index.ts#L281-L286).
=> chore: make SimpleServer not return an empty response for 404

src/Common/Version.props, src/Playwright.TestingHarnessTest/package-lock.json, src/Playwright.TestingHarnessTest/package.json
For reference, https://github.com/microsoft/playwright/commit/4860bcbfb92826e8ca805c07f950f7f5cd4cf8d2 was cherry-picked into the release-branch of microsoft/playwright.
=> chore: roll to Playwright v1.52.0

src/Playwright.Tests/BrowserContextRouteTests.cs, src/Playwright.Tests/FrameGoToTests.cs, src/Playwright.Tests/HARTests.cs, src/Playwright.Tests/PageRouteTests.cs, src/Playwright.Tests/UnrouteBehaviorTests.cs
Closes https://github.com/dotnet/sdk/issues/49116
=> test: reformat using latest formatter to avoid diffs

src/Playwright.CLI/Playwright.CLI.csproj, src/Playwright.MSTest.v4/Playwright.MSTest.v4.csproj, src/Playwright.MSTest/Playwright.MSTest.csproj, src/Playwright.NUnit/Playwright.NUnit.csproj, src/Playwright.TestAdapter/Playwright.TestAdapter.csproj, src/Playwright.Xunit.v3/Playwright.Xunit.v3.csproj, src/Playwright.Xunit/Playwright.Xunit.csproj, src/Playwright/Playwright.csproj
=> chore: add README.md to package metadata for all projects
