src/PlaywrightSharp.Abstractions/IBrowser.cs
src/PlaywrightSharp.Abstractions/IBrowserContext.cs
src/PlaywrightSharp.Abstractions/IPage.cs
src/PlaywrightSharp.TestServer/PlaywrightSharp.TestServer.csproj
src/PlaywrightSharp.TestServer/SimpleCompressionMiddleware.cs
src/PlaywrightSharp.TestServer/SimpleServer.cs
src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBaseTest.cs
src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserBaseTest.cs
src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserContextBaseTest.cs
src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpLoaderCollection.cs
src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpLoaderFixture.cs
src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpPageBaseTest.cs
src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj
src/PlaywrightSharp.Tests/TestConstants.cs
src/PlaywrightSharp.sln

Tests project setup

---

README.md

prettify readme

---

src/PlaywrightSharp.Abstractions/ClickOptions.cs
src/PlaywrightSharp.Abstractions/IKeyboard.cs
src/PlaywrightSharp.Abstractions/WaitForOption.cs
src/PlaywrightSharp.Chromium/Input/ChromiumRawKeyboard.cs
src/PlaywrightSharp.Chromium/PlaywrightSharp.Chromium.csproj
src/PlaywrightSharp.Chromium/Protocol/Protocol.Generated.cs
src/PlaywrightSharp.Firefox/Input/FirefoxRawKeyboard.cs
src/PlaywrightSharp.Firefox/Protocol/Protocol.Generated.cs
src/PlaywrightSharp.ProtocolTypesGenerator/Chromium/ChromiumProtocolTypesGenerator.cs
src/PlaywrightSharp.ProtocolTypesGenerator/Firefox/FirefoxProtocolTypesGenerator.cs
src/PlaywrightSharp.ProtocolTypesGenerator/ProtocolCodeGeneratorUtilities.cs
src/PlaywrightSharp.Tests/ElementHandle/ElementHandleFillTests.cs
src/PlaywrightSharp/ElementHandle.cs
src/PlaywrightSharp/Frame.cs
src/PlaywrightSharp/Input/IRawKeyboard.cs
src/PlaywrightSharp/Input/Keyboard.cs
src/PlaywrightSharp/Page.cs

Part of #57
I had to add `Macross.Json.Extensions` as a dependency because `System.Text.Json"  doesn't support custom enum values yet, see https://github.com/dotnet/runtime/issues/31081.
I added it only in the Chromium project,  I think it would end up also in Firefox and WebKit, but it's not needed by the rest of the projects, that's why I didn't add it to the common props.

Pass ElementHandleFill tests

---

src/PlaywrightSharp.Abstractions/IBrowser.cs
src/PlaywrightSharp.Abstractions/PlaywrightSharp.Abstractions.csproj
src/PlaywrightSharp.Chromium/ChromiumBrowser.cs

Fixes #272 
The reference to  `Microsoft.Bcl.AsyncInterfaces` doesn't need to be explicit as it is pulled in via `System.Text.Json`, happy to keep it in or remove it 😃

Remove conditional compilation around DisposeAsync

---

src/PlaywrightSharp.Tests/Page/ClickTests.cs

in playwright they just verify that a simple catch is enough without checking which specific error is thrown

fix flaky test

---

src/PlaywrightSharp.Firefox/FirefoxBrowserContext.cs
src/PlaywrightSharp.Tests/BrowserContext/GeolocationTests.cs

closes #103 
this is not supported yet on firefox so none of the tests actually run 😄

Firefox: Pass GeolocationTests

---

src/PlaywrightSharp.Tests/BaseTests/PlaywrightSharpBrowserLoaderFixture.cs
src/PlaywrightSharp.Tests/Page/NetworkIdleTests.cs

Playwright removed networkidle2 support here https://github.com/microsoft/playwright/pull/1883
We are not removing that feature yet. But simplifying our tests will bring us more stability.
closes #367

Remove networkidle2 tests

---

src/PlaywrightSharp/Helpers/StringExtensions.cs
src/PlaywrightSharp/PlaywrightSharp.csproj
src/PlaywrightSharp/Route.cs

Reused existing code to replace the need for `Microsoft.AspNetCore.StaticFiles`.
Also removed old `InternalsVisibleTo` attributes to the legacy projects.

Remove Microsoft.AspNetCore.StaticFiles dependency

---

src/PlaywrightSharp.Tests/Chromium/OopifTests.cs
src/PlaywrightSharp.Tests/Emulation/PageEmulateTests.cs
src/PlaywrightSharp/BrowserContextOptions.cs
src/PlaywrightSharp/DeviceDescriptor.cs

This will help users to simplify `NewContextAsync` calls when starting from a device descriptor.
```cs
await using var context = await _browser.NewContextAsync(new BrowserContextOptions(Playwright.Devices["iPhone 6"])
{
TimezoneId = "America/Jamaica",
Locale = "fr-CH",
UserAgent = "UA",
});
```

feat(context): improve BrowserContextOptions constructor

---

src/PlaywrightSharp.Tests/Internals/FlexibleStringEnumConverterTests.cs
src/PlaywrightSharp.Tests/Issues/Issue983.cs
src/PlaywrightSharp/Helpers/FlexibleStringEnumConverter.cs
src/PlaywrightSharp/Helpers/JsonExtensions.cs
src/PlaywrightSharp/ResourceType.cs

I added two new enums but I made the ResourceType parsing flexible. It will default to `Unknown` if the enum item is missing.
closes #983

fix(request): make ResourceType flexible

---

src/PlaywrightSharp.TestServer/SimpleServer.cs

Firefox tests were failing due to this.

fix(testserver): send back websocket close on close

---

src/Common/PackageInfo.props

We need to turn off the default excludes so we can include the new unpacked drivers.

fix(package): fix package generation

---

src/PlaywrightSharp/build/netstandard2.0/PlaywrightSharp.targets

i have noticed a typo in the runtimes directory for x86 builds - was x89

Update PlaywrightSharp.targets (x89 typo)

---

src/PlaywrightSharp/Transport/Connection.cs

the usage of WaitForObjectWithKnownNameAsync implies not null

WaitForObjectWithKnownNameAsync should not be null

---

src/PlaywrightSharp/ElementHandle.cs
src/PlaywrightSharp/Frame.cs
src/PlaywrightSharp/IElementHandle.cs
src/PlaywrightSharp/IFrame.cs
src/PlaywrightSharp/IJSHandle.cs
src/PlaywrightSharp/IPage.cs
src/PlaywrightSharp/IWorker.cs
src/PlaywrightSharp/JSHandle.cs
src/PlaywrightSharp/Page.cs
src/PlaywrightSharp/Worker.cs
src/PlaywrightSharp/runtimes/expected_api_mismatch.json

the api.json has some fields prepared for the new generation, ignoring them.
closes : #1163

codegen: ignore websocket fields

---

src/Common/PackageInfo.props
src/PlaywrightSharp.Tests/BeforeUnloadTests.cs
src/PlaywrightSharp.Tests/BrowserContextExposeFunctionTests.cs
src/PlaywrightSharp.Tests/BrowserContextPageEventTests.cs
src/PlaywrightSharp.Tests/HarTests.cs
src/PlaywrightSharp.Tests/NetworkPostDataTests.cs
src/PlaywrightSharp.Tests/SelectorsTextTests.cs
src/PlaywrightSharp/Request.cs

- Introduces `NetworkPostDataTests`
- Ports the `postData` fix
- Moves the driver to `1.10.0-next-1615194558000`
- Fixes #1265

fix(postData): add more network tests

---

CONTRIBUTING.md
src/Playwright/build/netstandard2.0/Microsoft.Playwright.targets

Adds a target to allow for faster running of interface generation.

chore(docs): run generator directly from msbuild

---

.build/azure-pipeline-nuget.yml

Splits the publish into stages & includes condition to releasing to NuGet.org to give back control over publishing.

chore(nuget): split publish into stages, add conditions

---

src/.editorconfig
src/Playwright.CLI/Program.cs

- Remove redundant code
- Use the NUGET_PACKAGES env variable, if one exists (as per .NET docs)
- dotnet format & warning cleanups
- remove var vs explicit type

chore: CLI cleanup

---

src/Playwright.NUnitTest/Playwright.NUnitTest.csproj
src/Playwright.Tests.TestServer/Playwright.Tests.TestServer.csproj

This removes warnings on the project about the referenced assemblies not having a strong name.

chore: add snk to test projects

---

.build/azure-pipeline-nuget.yml
Directory.Build.props
src/Playwright.CLI/Playwright.CLI.csproj
src/Playwright.NUnit/Playwright.NUnit.csproj
src/Playwright/Playwright.csproj

- Move the CI/symbols properties to the `Directory.Build.Props` file to apply it to all projects
- Generate the nupkg and snupkg and push together
- Remove the old notation of `*.Symbols.nupkg`

chore: clean-up & unify build/pack properties

---

src/Playwright/build/Microsoft.Playwright.targets

Clean-up our Drivers folder, potentially the DriversRaw folder for devs, and the incorrectly copied node and package folders. It also fixes an issue where we copied `node` and `package` folder over to the root of the output dir, instead of inside the `.playwright` folder.

chore: be a good citizen and perform a cleanup task

---

src/Common/Version.props

Moving the assembly version to `1.14` after 1.13 release.

chore(roll): update assembly version to next

---

README.md

(the text-based emojis do not render everywhere thats why we switched to the utf8 variants a while ago)

docs: fixed browser names in readme matrix

---

.build/azure-pipeline-nuget.yml
.github/workflows/tests.yml
CONTRIBUTING.md
build.ps1
src/Playwright/Playwright.csproj

Fix NETSDK1174 warning when building with the .NET 6 SDK (specifically, `6.0.100-preview.7.21379.14`).
```sh
Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.
```

chore: fix .NET SDK warning

---

src/Playwright/Core/Artifact.cs
src/Playwright/Core/Download.cs
src/Playwright/Core/Stream.cs
src/Playwright/Transport/Channels/StreamChannel.cs
src/Playwright/Transport/Connection.cs

This brings the naming inline with `protocol.yml` and the channels and their base objects are now consistent. This will make it easier to generate.

chore: rename PlaywrightStream to Stream to ensure naming consistency

---

src/Playwright/Helpers/JsonExtensions.cs

When generating, I'll make use of this helper, as it saves a bunch of boilerplate code in several calls.

chore: introduce optional string helper

---

src/Playwright.Tests/PageNetworkResponseTests.cs

TLS version mismatch on platforms is causing the test to be flaky yet the assertion provides no extra value

fix: improve flakiness due to TLS versions

---

src/Playwright.CLI/Playwright.CLI.csproj

Add `netcoreapp3.1` as a Target Framework so there is a supported LTS release targeted by the CLI tool once .NET Core 2.1 goes out of support [later this month](https://devblogs.microsoft.com/dotnet/net-august-2021/#net-core-2-1-end-of-life).

chore(cli): target netcoreapp3.1

---

src/Playwright.CLI/Playwright.CLI.csproj
src/Playwright.CLI/Program.cs
src/Playwright/Helpers/Paths.cs
src/Playwright/Program.cs

Closes #1694 
This patch stops the CLI from loading the DLL, which was causing problems with projects targeting .NET Framework 4.8 and instead relies on the `.playwright` folder existing somewhere underneath the root, or specified project path.

fix(CLI): use drivers instead of loading dll

---

src/Playwright/Program.cs

This breaks playwright.ps1 altogether.

Revert "fix(cli): fix .NET's escaping of quotes in cli args (#1655)"

---

src/Playwright/build/Microsoft.Playwright.targets

This code attempted to clean up old Drivers and DriversRaw folders that we left inside the root of the project directory.
We do not own the project directory. There might be important files in these folders! Any legacy playwright files
will just have to stay there.
Fixes #1802

fix: dont delete Drivers folder on build

---

src/Playwright/build/playwright.ps1

Use [`Join-Path`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.2) so that the correct path delimiter is used for the executing platform, rather than concatenating two strings and making assumptions.

chore: use Join-Path in PS1 script

---

src/Playwright.CLI/Playwright.CLI.csproj
src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.csproj
src/Playwright.TestingHarnessTest/Playwright.TestingHarnessTest.csproj
src/Playwright.Tests.TestServer/Playwright.Tests.TestServer.csproj
src/Playwright.Tests/NetworkPostDataTests.cs
src/Playwright.Tests/Playwright.Tests.csproj
src/Playwright.Tests/TracingTests.cs
src/Playwright.Tests/Utils/ScaffoldTest.cs
src/Playwright/Helpers/JsonExtensions.cs
src/Playwright/Playwright.csproj
src/tools/Playwright.Tooling/Playwright.Tooling.csproj

(all generated automatically by the Visual Studio Dependency Upgrade feature)
Extracted from #1884.
Failing bots are unrelated.

chore: bump dependencies

---

src/Playwright/Core/BrowserType.cs
src/Playwright/Playwright.cs
src/Playwright/Transport/Channels/BrowserContextChannel.cs
src/Playwright/Transport/Channels/FrameChannel.cs
src/Playwright/Transport/Channels/JSHandleChannel.cs
src/Playwright/Transport/Channels/JsonPipeChannel.cs
src/Playwright/Transport/Channels/PageChannel.cs
src/Playwright/Transport/Channels/ResponseChannel.cs
src/Playwright/Transport/Connection.cs

Currently new connection specifc `JsonSerializerOptions` are always created but they can just be reused instead.

reuse Connection JsonSerializerOptions

---

src/Playwright/Core/Waiter.cs

as it is one of the APIs which is in `netstandard2.0` but not in `net461`
With this fix I can use Playwright on `net461`.
Here is a simple testcase to reproduce the issue:
```c#
Microsoft.Playwright.Program.Main(new[] { "install" });
var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
var browser = await playwright.Chromium.LaunchAsync();
var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
page.FrameNavigated += async (sender, frame) =>
{
await frame.WaitForLoadStateAsync(); // this will throw
};
await page.GotoAsync("https://google.de");
```
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>Exe</OutputType>
<TargetFramework>net461</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable> …
```

avoid Enumerable.Prepend

---

src/Playwright.Tests/BrowserTypeConnectTests.cs
src/Playwright.Tests/Playwright.Tests.csproj
src/Playwright/Helpers/Driver.cs
src/Playwright/Program.cs
src/Playwright/Transport/StdIOTransport.cs

Fixes #1932
Example values:
```
PW_CLI_TARGET_LANG_VERSION: '6.0.0',
PW_CLI_TARGET_LANG: 'csharp',
PW_CLI_DISPLAY_VERSION: '1.17.1',
```

chore: set driver environment variables

---

src/Playwright.Tests/BrowserContextRouteTests.cs
src/Playwright.Tests/PageRouteTests.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/Page.cs
src/Playwright/Core/RouteSetting.cs

Currently route urls are converted to regular expressions on every route match which could result in a regex parse exception if the url is invalid.
With this change the regex is created once when the url route is added which means that potential regex parse exceptions are thrown immediately instead of later when the route is matched.
This also fixes a case where it wasn't possible to remove a url route when the browsing context has a base url set.
This also synchronized the code style for adding routes in `BrowserContext` and `Page`.

create Route glob regex immediately

---

src/Playwright.Tests/TracingTests.cs
src/Playwright/Core/Tracing.cs

cherry-pick(release-1.18): fix: save trace without path

---

src/Playwright/build/Microsoft.Playwright.targets

This will by default only copy the node platform folder for the current platform.
The `RuntimeIdentifier` will override it, so you could do:
```
dotnet publish -r linux-x64
dotnet publish -r win-x64
dotnet publish -r osx-x64
```
and it will copy the correct platform folder even when the command is run on another platform. Even
```
dotnet publish -r ubuntu-x64
```
works because `RuntimePack.RuntimeIdentifier` will resolve to `linux-x64`.
To go back to the old behavior of copying all node platforms add the following to your project file:
```xml
<PropertyGroup>
<PlaywrightPlatform>all</PlaywrightPlatform>
</PropertyGroup>
```` 
If the platform is unknown (which includes `all`) it will also copy everything.
There is also the option of not copying the `.playwright` folder at all by using: …

copy node folder based on platform

---

src/Playwright.Tests/PageRequestContinueTests.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/Page.cs
src/Playwright/Core/Route.cs

Backports: https://github.com/microsoft/playwright/commit/3cc839e01327dbf5b6e2a889da8da373b7efd503
Extracted from: #1938
Relates #1754
We'll follow-up on the unhandled exceptions once we add the bot for it in upcoming patches.

chore: catch all route methods when page closes

---

.github/workflows/tests.yml
src/Playwright.Tests/Attributes/PlaywrightTestAttribute.cs
src/Playwright.Tests/BrowserContextCSPTests.cs
src/Playwright.Tests/DefaultBrowserContext1Tests.cs
src/Playwright.Tests/DefaultBrowsercontext2Tests.cs
src/Playwright.Tests/DownloadTests.cs
src/Playwright.Tests/DownloadsPathTests.cs
src/Playwright.Tests/Helpers/TempDirectory.cs
src/Playwright.Tests/PageClickTimeout2Tests.cs
src/Playwright.Tests/PageGotoTests.cs
src/Playwright.Tests/PageRouteTests.cs
src/Playwright.Tests/TestUtils.cs
src/Playwright.Tests/TracingTests.cs
src/Playwright/Core/BrowserType.cs
src/Playwright/Core/Frame.cs
src/Playwright/Core/Waiter.cs
src/Playwright/Helpers/TaskHelper.cs

- Adds an `TaskScheduler.UnobservedTaskException` event handler for each test to check if there are any unobserved exceptions
- Sets `[LevelOfParallelism(1)]` to ensure that each test is run in sequence. This was already the case for CI where `NUnit.NumberOfTestWorkers=1` is used, which now could be removed. And now it also applies when run locally.
https://github.com/microsoft/playwright-dotnet/blob/c12b4fcd8061b396ef4d4587dafd9b876202f009/.github/workflows/tests.yml#L42
- Add `IgnoreException` utility which marks all exceptions as handled if a task faulted.
- Fixes dispose order for browser / browsercontext and tempdirectory to avoid unnecessary exceptions. Deleting the tempdirectory before disposing the browser throws a `UnauthorizedAccessException`.
Fixes #1963

chore: ensure no unhandled exceptions are thrown

---

src/Playwright/Core/Locator.cs

`Locator.AllInnerTextAsync` / `Locator.AllTextContentAsync` didn't dispose the intermediate `IElementHandle` objects which is what the first commit fixes.
The second commit changes these to use `Locator.EvaluateAllAsync` instead so there are no intermediate objects created in the first place which results in better performance and memory usage.
This is also what the JS version is using:
https://github.com/microsoft/playwright/blob/0606afb2e66737a352cf8627fa0260ea2fceb267/packages/playwright-core/src/client/locator.ts#L241
https://github.com/microsoft/playwright/blob/0606afb2e66737a352cf8627fa0260ea2fceb267/packages/playwright-core/src/client/locator.ts#L245
Please let me know which version is preferred.

update Locator AllInnerText / AllTextContent

---

src/Playwright.Tests/PageRequestContinueTests.cs
src/Playwright/Core/Route.cs
src/Playwright/Helpers/TaskHelper.cs

follow up to https://github.com/microsoft/playwright-dotnet/pull/1973#discussion_r793594152
also added test from https://github.com/microsoft/playwright/blob/5ba7903ba098586a13745e0d7ac894f1d55d47aa/tests/page/page-request-continue.spec.ts#L65-L78

don't suppress route exceptions when page is still open

---

src/Playwright.Tests/PageExposeFunctionTests.cs
src/Playwright/Core/BindingCall.cs

Before non generic tasks and `VoidTaskResult`s were serialized as JSON objects which does not make much sense so lets treat them as `null` instead. E.g. `Task.CompletedTask` / `Task.Delay` or in general `Func<Task>`.
`Task.CompletedTask` is actually a [`Task<VoidTaskResult>`](https://github.com/dotnet/runtime/blob/6233735c37b1af9c182c28c9d74aeac0104785b8/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1457-L1462). 
`Task.Delay` is a real [`Task`](https://github.com/dotnet/runtime/blob/6233735c37b1af9c182c28c9d74aeac0104785b8/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5569-L5570).
A similar change was committed to a similar library: https://github.com/cefsharp/CefSharp/commit/cd225bc1697cc3001d4aa4c7e9ca4ac85a0cd810

treat non generic Task and VoidTaskResult as null in Binding

---

src/Playwright/Transport/ChannelOwnerBase.cs

Align with upstream: https://github.com/microsoft/playwright/blob/f82e09be044c78c04964162aeda3e03d82c1ed06/packages/playwright-core/src/client/channelOwner.ts#L68
`ConcurrentDictionary.Values` returns a new list which is why it didn't throw: 
https://github.com/dotnet/runtime/blob/ef817df491e87d1d5ffcd12e78d48c6520430be2/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L2142-L2174

ChannelOwnerBase: move _objects.Clear() out of loop

---

src/Playwright/Playwright.csproj

It is only needed for `netstandard2.0`.

remove Microsoft.Bcl.AsyncInterfaces reference from net5.0

---

.build/azure-pipeline-nuget.yml
.github/workflows/code-style.yml
.github/workflows/nuget-package-tests.yml
.github/workflows/smoke-tests.yml
.github/workflows/tests.yml
src/.editorconfig
src/Common/Dependencies.props
src/Playwright/Core/Artifact.cs
src/Playwright/Playwright.csproj
src/Playwright/Transport/Connection.cs
src/tools/Playwright.Tooling/Playwright.Tooling.csproj

Fixes https://github.com/microsoft/playwright-dotnet/issues/1974
Relates https://github.com/microsoft/playwright-dotnet/pull/1884
Motivation: .NET 5 reaches EOL in May 8, 2022 since it was no LTS, LTS is .NET 6. There are no changes in the TFM so no user facing changes and only tooling.

chore: migrate tooling over to .NET 6

---

src/Playwright/Transport/StdIOTransport.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/1998
(When the redirected stream is closed, a null line is sent to the event handler. see [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.datareceivedeventhandler?view=net-6.0#remarks)

fix: do not empty line on stderr on close

---

src/Playwright/build/Microsoft.Playwright.targets

chore: don't include PlaywrightCopyItems in pack

---

src/Playwright.Tests/PageEvaluateTests.cs
src/Playwright.Tests/Playwright.Tests.csproj
src/Playwright/Helpers/EnumHelper.cs
src/Playwright/Helpers/JsonExtensions.cs
src/Playwright/Playwright.csproj
src/Playwright/Transport/Converters/JsonStringEnumMemberConverter.cs
src/tools/Playwright.Tooling/Playwright.Tooling.csproj

Now using a custom `JsonStringEnumMemberConverter` which calls the existing `ToValueString` helper and adds a corresponding `FromValueString`.
Fixes #2019

chore: drop Macross.Json.Extensions from dependencies

---

src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs

which avoids creating intermediate arrays and coping between them.
The second commit uses `GetArrayLength` so the typed array can be directly created without going through an `ArrayList` first.

chore: simplify ParseEvaluateResult for arrays

---

src/Playwright.Tests/BrowserContextStorageStateTests.cs
src/Playwright/Core/BrowserContext.cs

which serializes enum values to strings and does not serialize null values
Fixes #2035

use DefaultJsonSerializerOptions in StorageStateAsync

---

src/Playwright/Transport/Connection.cs

https://docs.microsoft.com/en-us/dotnet/api/system.type.namespace?view=net-6.0
> Namespace: The namespace of the [Type](https://docs.microsoft.com/en-us/dotnet/api/system.type?view=net-6.0); null if the current instance has no namespace or represents a generic parameter.
```
System.NullReferenceException: Object reference not set to an instance of an object.
System.NullReferenceException
Object reference not set to an instance of an object.
at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 443
at Microsoft.Playwright.Transport.Channels.Root.InitializeAsync() in /_/src/Playwright/Transport/Channels/Root.cs:line 47
at Microsoft.Playwright.Playwright.CreateAsync() in …
```

check namespace for null

---

src/Playwright.Tests/CLITests.cs
src/Playwright/Program.cs

Current state/implementation (ToT) when invoking the CLI:
```
CreateNoWindow = true,
RedirectStandardError = true,
RedirectStandardInput = true,
RedirectStandardOutput = true,
```
(properties when calling the Playwright CLI via our ps1 script or Playwright CLI.
This ends up that the stdout/stderr stream does end up in `OutputDataReceived` and `ErrorDataReceived` which has the downside that `isTTY` on `Node.js` side is `false`. -> No progress bar when downloading browsers.
New implementation:
```
CreateNoWindow = false,
RedirectStandardError = false,
RedirectStandardInput = false,
RedirectStandardOutput = false,
```
(leaving defaults there so its easier understandable). When specifying these values to false, `they` get automatically written to `Process.StandardOutput` and friends. Thats …

chore: do not redirect stdout/stderr in CLI

---

src/Playwright/build/Microsoft.Playwright.targets

which copies files correctly when using `publish`.
- `CopyRuntimeConfigToOutput` is no longer needed as there is no runtime config for `netstandard2.0`. (It was needed for NET 3.1/5/6 etc.)
- `PlaywrightBuildCleanup` is no longer needed because `Content` files are automatically part of the `clean` target.
- `PlaywrightPlatform` does not affect `playwright.ps1`.
Fixes #2098

Use ItemGroup for copying playwright.ps1

---

src/Playwright/build/Microsoft.Playwright.targets

Fixes https://github.com/microsoft/playwright-dotnet/issues/2109

chore: include RuntimeIdentifier when publishing nuget

---

src/Playwright/Program.cs

Before this change the progress bar was broken on Windows, due the default encoding did not process the progress bar character correctly. It looked like this:
This change fixes it.

fix: fix progress bar reporting on Windows

---

src/Playwright.Tests.TestServer/SimpleServer.cs

Before this change some tests were failing where concurrent file reads were involved on the same file see the following picture:
This fixes it.

test: fix flaky tests with concurrent file reads on test server

---

src/Playwright.Examples/Playwright.Examples.csproj
src/Playwright.Examples/Program.cs

Testing some actual user code without needing to build the nuget locally and installing it in a non trivial way in a new folder was hard.
We have now a small little playground where we can run user-code which uses the Playwright package right from the source-code.

chore: add local library playground

---

.build/azure-pipeline-nuget.yml
.github/ISSUE_TEMPLATE/bug.md

I made a dry run which was working fine.
This was our last remainder for the .NET 6 tooling migration.

devops: use .NET 6 for publishing

---

src/Playwright.MSTest/BrowserTest.cs
src/Playwright.MSTest/ContextTest.cs
src/Playwright.MSTest/PageTest.cs
src/Playwright.MSTest/Services/BrowserService.cs
src/Playwright.NUnit/BrowserService.cs
src/Playwright.NUnit/BrowserTest.cs
src/Playwright.NUnit/ContextTest.cs
src/Playwright.NUnit/PageTest.cs
src/Playwright.NUnit/Playwright.NUnit.csproj
src/Playwright.NUnit/PlaywrightTest.cs
src/Playwright.NUnit/WorkerAwareTest.cs

This aligns it with our NUnit harness. When users used it before, it always yelled with "hey Page can be null" warning.

chore(mstest): make page/context/browser non-nullable

---

src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.csproj
src/Playwright.MSTest/Playwright.MSTest.csproj
src/Playwright.NUnit/Playwright.NUnit.csproj
src/Playwright/Playwright.csproj

As per https://github.com/microsoft/playwright-dotnet/pull/1917#issuecomment-1012009922 (since .NET 6 is now LTS) we can now upgrade the NUnitAdapter and other dependencies to get rid of the miss-matching compatibility.
Once this is merged, I'll follow up with a manual test to make sure the nunit/mstest packages still works as expected.

chore: bump prod dependencies

---

src/Playwright.MSTest/Playwright.MSTest.csproj
src/Playwright.NUnit/Playwright.NUnit.csproj
src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs

This makes playwright-dotnet work with dotnet sdk 6.0.201 which you get with a default GitHub Codespace.

chore: release dry-run fixes

---

.gitignore
src/Playwright/Playwright.csproj

Removes `Microsoft.Playwright.targets` import from `Playwright.csproj` and inline `DedupeDriver` using `ItemGroup`s with `CopyToOutputDirectory` / `Pack` attributes instead of using `Copy`. Similar to `Microsoft.Playwright.targets`.
Supersedes #2267 and #2268
Fixes #2271

chore: fix dotnet build did not pack the same results as dotnet pack

---

src/Playwright/build/Microsoft.Playwright.targets

`linux` folder got renamed to `linux-x64`.
It didn't find any files in the linux folder so as a fallback it just copied everything.
Fixes #2289

chore: fix linux-x64 copy items

---

src/Playwright/Core/BrowserType.cs
src/Playwright/Core/PlaywrightImpl.cs
src/Playwright/Playwright.cs
src/Playwright/Transport/Connection.cs

Apply the upstream https://github.com/microsoft/playwright/pull/9524 patch.
Drive-by fix specific connect waiter.cs tests. For the actual fox of them see the comment related to `callback.Value.TaskCompletionSource.Task.IgnoreException();`.

chore: align connection close with upstream impl

---

src/tools/Playwright.Tooling/DriverDownloader.cs

This should help us to understand [this](https://github.com/microsoft/playwright-dotnet/actions/runs/3039803653/jobs/4895150780). It's not user-facing, only we on our CI workflows and dev workflows download the driver, for users we ship it inside the nupkg file.

chore: verify for status code 200 when downloading driver

---

src/Playwright/build/Microsoft.Playwright.targets

Which will run the `CopyPlaywrightFilesToOutput` target also on `publish --no-build`.
Fixes #2354

chore: use ResolveAssemblyReferences instead of BeforeBuild

---

src/Common/Version.props
src/Playwright.MSTest/PlaywrightTest.cs
src/Playwright.NUnit/PlaywrightTest.cs
src/Playwright.Tests/BaseTests/PlaywrightTestEx.cs
src/Playwright.Tests/Locator/LocatorFrameTests.cs
src/Playwright.Tests/SelectorGeneratorTests.cs
src/Playwright.Tests/SelectorsGetByTests.cs
src/Playwright/Core/BrowserType.cs
src/Playwright/Core/Frame.cs
src/Playwright/Core/FrameLocator.cs
src/Playwright/Core/Locator.cs
src/Playwright/Core/PlaywrightImpl.cs
src/Playwright/Core/Selectors.cs
src/Playwright/Transport/Channels/SelectorsChannel.cs

- Add GetByRole Exact
- align selectors handling with upstream
- remove legacy namespace declaration in some of the channels (the rest is good already) moved out into https://github.com/microsoft/playwright-dotnet/pull/2391.

chore: roll to 1.28.0-beta-1668538774000

---

src/Playwright/Program.cs

We only had it because we had CreateNoWindow=true and it was added in https://github.com/microsoft/playwright-dotnet/pull/1426. Let's not add it to actually forward the stderr/stdout how it should be.
I tested it that it does not produce any console window etc.

chore: simplify Playwright CLI

---

src/Playwright/Helpers/Driver.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2479 
Was unable to create an automated test as unsure how to alter `AppContext.BaseDirectory` without taking a complex dependency on my loading scenario. Was manually tested by loading the built `Microsoft.Playwright.dll` into a script. The fix is straightforward.

fix: Handle case when AppContext.BaseDirectory is empty

---

src/Playwright.Tests/PageRequestInterceptTests.cs
src/Playwright/Core/Route.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2506

fix: be able to call Route.FetchAsync() without args

---

src/Playwright/Transport/StdIOTransport.cs

This fixes the following which was shown when debugging a .NET program using Playwright and a playwright.close was happening.:
```log
System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at System.Threading.CancellationToken.ThrowIfCancellationRequested()
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
at Microsoft.Playwright.Transport.StdIOTransport.GetResponseAsync(CancellationToken …
```

chore: swallow OperationCanceledException in transport

---

src/Playwright/build/Microsoft.Playwright.targets

The item `<_PlaywrightPlatforms Include="$(PlaywrightPlatform)" />` will split the `PlaywrightPlatform` property by `;` and so each entry can be checked individually with `%(_PlaywrightPlatforms.Identity)` which is better than using `Contains`.
Fixes #2525
@mxschmitt It looks like with version 1.32.0 the `mac` package was renamed to `darwin` in the nuget and the changes done in #2500 look wrong to me for the `Microsoft.Playwright.targets` file.
Maybe this needs a 1.32.1 release?

chore: use darwin folder on osx and replace contains with identity check

---

src/Playwright.Tests/PageRequestFulfillTests.cs
src/Playwright/Helpers/TaskHelper.cs

Enable tests that use screenshots as they work.
Removing a warning.
Fixes https://github.com/microsoft/playwright-dotnet/issues/2541

test: enable tests that use screenshots as they work.

---

src/Playwright.Tests/Locator/LocatorConvenienceTests.cs
src/Playwright/Transport/Channels/ElementHandleChannel.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2566

fix: fix ElementHandle.GetAttributeAsync when attribute does not exist

---

src/Playwright/Program.cs

After net8.0-preview4 https://github.com/dotnet/runtime/pull/82662 got landed upstream, which adds support for WindowStyle when Shell=false (default). This fixes the customer reported issue for us. It should not regress any behaviour for previous .NET users, so we can always set this flag when the CLI gets invoked.
Note: This does not require us to change any TFM. Only the customers need to use net8-preview4+. (which is LTS in November this year).
Appreciate the work @Jozkee and cc @nohwnd.
Fixes https://github.com/microsoft/playwright-dotnet/issues/2462
Relates https://github.com/microsoft/playwright-dotnet/pull/2489
Closes https://github.com/dotnet/runtime/issues/68259#issuecomment-1605093489 (not needed anymore).

fix: hide cmd.exe window when invoking CLI programmatically

---

src/Playwright.Tests/ConventionTests.cs
src/Playwright/Core/APIRequestContext.cs
src/Playwright/Core/Artifact.cs
src/Playwright/Core/Browser.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/BrowserType.cs
src/Playwright/Core/CDPSession.cs
src/Playwright/Core/Dialog.cs
src/Playwright/Core/Frame.cs
src/Playwright/Core/JSHandle.cs
src/Playwright/Core/JsonPipe.cs
src/Playwright/Core/Page.cs
src/Playwright/Core/Request.cs
src/Playwright/Core/Response.cs
src/Playwright/Core/Route.cs
src/Playwright/Core/Stream.cs
src/Playwright/Core/Tracing.cs
src/Playwright/Core/Worker.cs
src/Playwright/Core/WritableStream.cs
src/Playwright/Transport/ChannelOwnerBase.cs
src/Playwright/Transport/Connection.cs

Fixes #2617 
I've recreated the issue locally on macOS on my M2 MBP, this fixes the exception, I need to check that the traces have the right API names captured still.

Prevent TieredPGO inlining from breaking stack trace walking logic

---

src/Playwright.Tests/ExtensionTests.cs
src/Playwright.Tests/Locator/LocatorQueryTests.cs
src/Playwright/Helpers/RegexOptionsExtensions.cs

fix: allow RegexOptions.Compiled in GetInlineFlags

---

src/Common/Dependencies.props
src/Playwright/Playwright.csproj

When this project changed from multitargeting to only targeting netstandard, it also lost all `Microsoft.CodeAnalysis.NetAnalyzers`.
See https://learn.microsoft.com/visualstudio/code-quality/install-net-analyzers?view=vs-2022
Ref: #2637

chore: enable Microsoft.CodeAnalysis.NetAnalyzers

---

src/Playwright/Transport/StdIOTransport.cs

https://github.com/microsoft/playwright-dotnet/issues/2663
Tested with a net6.0-windows WinForms application, was able to reproduce it without the fix and it worked after the fix.

fix: init without console

---

src/Playwright.Tests/BrowserContextFetchTests.cs
src/Playwright/Core/FormData.cs
src/Playwright/Transport/Channels/APIRequestContextChannel.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2662
This might affect Java as well.

fix: throw when serializing FilePayload in Form Fetch request

---

CONTRIBUTING.md
src/Playwright.Tests/ScreencastTests.cs
src/Playwright/Core/Video.cs

The issue was that the artifact came after the page close event has fired. So it was waiting for a page.close event inside the Video.cs but it already arrived, so it stalled.
Fixes https://github.com/microsoft/playwright-dotnet/issues/2658
Closes https://github.com/microsoft/playwright-dotnet/pull/2664

fix: video.PathAsync() should not hang after direct launch/close

---

src/Playwright/build/Microsoft.Playwright.targets

[Windows RIDs / RuntimeIdentifier are `win-x64` / `win-x86`](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#windows-rids). Specifying `PlaywrightPlatform=win` still worked.
Not sure why I missed that in #2531
Fixes #2687

chore: fix windows PlaywrightPlatform detection

---

src/Playwright.Tests/PageEvaluateTests.cs
src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs

To make it easier to debug issues like #2701 because `Activator.CreateInstance` can throw for a lot of different reasons.
The issue there is that there is no parameterless constructor which playwright requires as it uses `Activator.CreateInstance`.

chore: pass Activator.CreateInstance exception as inner exception

---

src/Playwright/Core/Page.cs

We do that in the other places too:
Fixes https://github.com/microsoft/playwright-dotnet/issues/2719

fix: return copy of list in IPage.Frames

---

src/Playwright/Playwright.csproj

This does it like the Azure CLI folks: https://github.com/Azure/azure-sdk-for-net/blob/ff337a1ce38c57f770d28a36198d90ad7be27f80/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/DigitalTwinsClientSample.csproj#L21
But this most likely will regress https://github.com/microsoft/playwright-dotnet/issues/2408 since it reverts https://github.com/microsoft/playwright-dotnet/pull/2410, requires testing.
Fixes https://github.com/microsoft/playwright-dotnet/issues/2696

fix: use minimum 6.0.0 System.Text.Json version

---

src/Playwright.Tests/BrowserTypeConnectTests.cs
src/Playwright/Helpers/Driver.cs
src/Playwright/Program.cs
src/Playwright/Transport/StdIOTransport.cs

* Since everything is static ("csharp" constant string + environment version + assembly version) the dictionary is only created once and thus changed from a method to a property.
* Using the built-in `Version.ToString(3)` instead of the equivalent custom method `GetSemVerPackageVersion`.

chore: Simplify the implementation of the driver environment variables

---

src/Playwright.Tests.TestServer/Playwright.Tests.TestServer.csproj

Since `Playwright.Tests.TestServer` uses `Microsoft.NET.Sdk.Web` they aren't needed.

chore: remove explicit Microsoft.AspNetCore PackageReferences from TestServer

---

src/Playwright/Core/Tracing.cs
src/Playwright/Transport/Channels/TracingChannel.cs

Since `NameValue` uses `JsonPropertyNameAttribute` I don't think the `PropertyNameCaseInsensitive = true` is needed anymore and the `_tracingChannelSerializerOptions` aren't needed.
https://github.com/microsoft/playwright-dotnet/blob/1322ae0e8679ced3ce2842dc8997800891be9cbf/src/Playwright/Transport/Protocol/Generated/NameValue.cs#L29-L36

chore: remove TracingChannel JsonSerializerOptions

---

.build/azure-pipeline-nuget.yml
.github/workflows/code-style.yml
.github/workflows/nuget-package-tests.yml
.github/workflows/publish_canary_docker.yml
.github/workflows/publish_release_docker.yml
.github/workflows/test_docker.yml
.github/workflows/tests.yml
.github/workflows/tests_harness.yml
CONTRIBUTING.md
src/Playwright.CLI/Playwright.CLI.csproj
src/Playwright.Examples/Playwright.Examples.csproj
src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.csproj
src/Playwright.MSTest/Playwright.MSTest.csproj
src/Playwright.NUnit/Playwright.NUnit.csproj
src/Playwright.TestAdapter/Playwright.TestAdapter.csproj
src/Playwright.TestingHarnessTest/Playwright.TestingHarnessTest.csproj
src/Playwright.Tests.TestServer/Playwright.Tests.TestServer.csproj
src/Playwright.Tests.TestServer/SimpleServer.cs
src/Playwright.Tests/PageEvaluateTests.cs
src/Playwright.Tests/Playwright.Tests.csproj
src/Playwright/Playwright.csproj
src/tools/Playwright.Tooling/Playwright.Tooling.csproj
utils/docker/Dockerfile.jammy

This gets merged around November 14-16, 2023, when .NET 8 is the new LTS.
Changes include:
- Do not target `netcoreapp3.1` anymore for the CLI, since its EOL, target .NET 6/ .NET 7/.NET 8 instead.
- These are the currently supported .NET versions
- dotnet tools only work under these two target frameworks
- Had to remove `GeneratePackageOnBuild` which made dotnet pack work, seems like not to have other bad side effects

chore: move to .NET 8 (LTS)

---

src/Playwright.LocalNugetTest/Playwright.LocalNugetTest.csproj
src/Playwright.TestingHarnessTest/Playwright.TestingHarnessTest.csproj
src/Playwright.Tests/Playwright.Tests.csproj

This broke the VSCode integration, so we had to bump it.
This does not affect any shipped/prod dependencies.

chore: update dev nunit dependencies

---

.github/workflows/publish_canary_docker.yml
.github/workflows/publish_release_docker.yml
utils/docker/Dockerfile.focal
utils/docker/Dockerfile.jammy
utils/docker/build.sh

As per https://github.com/dotnet/runtime/issues/95120 QEMU is not supported. We'll instead cross-compile in the outside and use it's artifacts inside the container.
This worked on my Ubuntu 22.04 machine when testing.

devops: fix .NET publishing

---

src/Playwright/Helpers/Driver.cs
src/Playwright/build/playwright.ps1

Motivation: If you run `playwright.ps1` inside a PowerShell session, the `Microsoft.Playwright.dll` got loaded but never unloaded. This resulted that the `Microsoft.Playwright.dll` file stayed open on Windows. Future calls to `dotnet build` or `dotnet clean` did misbehave.
Fix: Read the content: around 1 MB and load the Assembly. This has the drawback that the program (when running the CLI) doesn't know anymore where it was running, so it is not able to find the `.playwright` path etc.

fix: Microsoft.Playwright.dll is in use

---

src/Common/Dependencies.props
src/Playwright.Tests/BrowserContextRouteTests.cs
src/Playwright.Tests/PageRouteTests.cs
src/Playwright/Core/Locator.cs

This fixes:
```
/Users/maxschmitt/.nuget/packages/microsoft.codeanalysis.netanalyzers/7.0.3/build/Microsoft.CodeAnalysis.NetAnalyzers.targets(593,5): warning : The .NET SDK has newer analyzers with version '8.0.0' than what version '7.0.3' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. [/Users/maxschmitt/Developer/playwright-dotnet/src/Playwright/Playwright.csproj]
CSC : warning SA0001: XML comment analysis is disabled due to project configuration (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md) [/Users/maxschmitt/Developer/playwright-dotnet/src/tools/Playwright.Tooling/Playwright.Tooling.csproj]
/Users/maxschmitt/Developer/playwright-dotnet/src/Playwright.Tests/BrowserContextRouteTests.cs(369,13 …
```

chore: get rid of build warnings

---

src/Playwright.NUnit/Playwright.NUnit.csproj
src/Playwright.NUnit/WorkerAwareTest.cs

This fixes:
```
/Users/maxschmitt/Developer/playwright-dotnet/src/Playwright.NUnit/Playwright.NUnit.csproj : warning NU1701: Package 'NUnit3TestAdapter 4.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [/Users/maxschmitt/Developer/playwright-dotnet/src/Playwright.sln]
All projects are up-to-date for restore.
/Users/maxschmitt/Developer/playwright-dotnet/src/Playwright.NUnit/Playwright.NUnit.csproj : warning NU1701: Package 'NUnit3TestAdapter 4.0.0' was restored using …
```

chore: align Microsoft.Playwright.NUnit TFM with NUnit3TestAdapter TFM

---

src/Playwright/build/Microsoft.Playwright.targets

Fixes https://github.com/microsoft/playwright-dotnet/issues/2827
My first attempt was using `OutDir` but it broke some of the LocalNugetTests. Instead we now call EnsureTrailingSlash.

fix: build with --output without trailing slash

---

src/Playwright.Tests/PdfTests.cs
src/Playwright/Core/Page.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2841

fix: PdfAsync without passing options

---

.github/workflows/code-style.yml
.github/workflows/nuget-package-tests.yml
.gitignore
build.sh
src/Playwright.Tests/InterceptionTests.cs
src/Playwright.Tests/Playwright.Tests.csproj
src/Playwright/Playwright.csproj
src/Playwright/Transport/Converters/ChannelOwnerConverterFactory.cs

Changes:
- Migrated to the new tool: https://github.com/dotnet/format/issues/1268.
- Exposing all internals to the test project
- Drive-by rename InterceptionTests

chore: migrate dotnet-format to dotnet format

---

src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs
src/Playwright.TestingHarnessTest/tests/baseTest.ts

We could warn as well, but it seems not a helpful warning where the user can act on.
Fixes https://github.com/microsoft/playwright-dotnet/issues/2847.

chore: improve invalid browser name by env exception

---

src/Playwright.MSTest/PlaywrightTest.cs
src/Playwright.NUnit/PlaywrightTest.cs
src/Playwright.Tests/Assertions/LocatorAssertionsTests.cs
src/Playwright/Assertions.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2259
Fixes https://github.com/microsoft/playwright-dotnet/issues/2603
~~Maybe we should introduce Expect().Configure like we have in Node.js: https://playwright.dev/docs/test-assertions#expectconfigure~~

feat: expose SetDefaultExpectTimeout()

---

.build/azure-pipeline-nuget.yml
.build/guardian/SDL/.gdnsuppress
src/Common/Version.props

See here: https://dev.azure.com/securitytools/SecurityIntegration/_wiki/wikis/Guardian/1385/Suppressions
The `.gdnsuppress` file got obtained during a previous test-run where it was in the artifacts section of the SDL stage. They are like `.eslintignore`, but instead of the file location, they contain the location, type, reason etc. in a hashed form, for security reasons.
When to update? When SDL checks are red in Azure Pipelines.
How to update? See the link, based on the artifact it can be just downloaded / replaced.
---
How is it tested? 1.42.0-beta-1 is published.

devops: migrate to 1ES PT

---

README.md
src/Common/Version.props
src/Playwright.Tests/BrowserContextClearCookiesTests.cs
src/Playwright.Tests/BrowserContextStorageStateTests.cs
src/Playwright.Tests/ElementHandleMiscTests.cs
src/Playwright.Tests/Locator/LocatorFrameTests.cs
src/Playwright.Tests/PageNetworkRequestTest.cs
src/Playwright/API/Generated/IBrowserContext.cs
src/Playwright/API/Generated/IFrameLocator.cs
src/Playwright/API/Generated/ILocator.cs
src/Playwright/API/Generated/IPage.cs
src/Playwright/API/Generated/Options/BrowserContextClearCookiesOptions.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchOptions.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchPersistentContextOptions.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/BrowserType.cs
src/Playwright/Core/FrameLocator.cs
src/Playwright/Core/JSHandle.cs
src/Playwright/Core/Locator.cs
src/Playwright/Core/Request.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2872

feat(roll): roll Playwright to 1.43.0-beta-1711484700000

---

src/Common/Version.props
src/Playwright.Tests/ChromiumLauncherTests.cs
src/Playwright/API/Generated/IBrowserContext.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/Page.cs

This was added after we rolled the last time.
https://github.com/microsoft/playwright-dotnet/issues/2896

feat(roll): roll Playwright to 1.43.0-beta-1712646596000

---

src/Playwright/Helpers/Driver.cs

Should not be any big logical changes, just safeguards the access to `assembly.CodeBase` and falls-back to `AppContext.BaseDirectory` otherwise which is important for the self-contained executables.
https://github.com/microsoft/playwright-dotnet/issues/2255

fix: support self-contained executables

---

src/Playwright/Core/CDPSession.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2912
Aligns it with JavaScript: https://github.com/microsoft/playwright/blob/82aefd24db1ba9977c3f6953347ee266845790ea/packages/playwright-core/src/client/cdpSession.ts#L31
And with Python: https://github.com/microsoft/playwright-python/pull/2411
And with Java: https://github.com/microsoft/playwright-java/pull/1553

fix(cdpSession): events without payload

---

src/Playwright.MSTest/PlaywrightTest.cs
src/Playwright.NUnit/PlaywrightTest.cs

Semantically its a breaking change, but since csharp does allow calling static methods like instance methods, it seems fine?
Looking e.g. at this test:
https://github.com/microsoft/playwright-dotnet/blob/c4b3dc42df71596240e9bc91068a5623ef72e14d/src/Playwright.Tests/Assertions/LocatorAssertionsTests.cs#L50-L64
Alternatively we can specify both methods (static and non-static version).
Fixes https://github.com/microsoft/playwright-dotnet/issues/2957

chore: make SetDefaultExpectTimeout static

---

src/Playwright.Tests/BrowserContextFetchTests.cs
src/Playwright/Core/APIRequestContext.cs
src/Playwright/Core/BrowserContext.cs

This ports the missing two patches:
- https://github.com/microsoft/playwright/commit/776b04e5ea1f2adcc82d9459cf593775662ef3e3
- https://github.com/microsoft/playwright/commit/e7a11c0ca22881623b073f2540c21b5d2da24085
Fixes https://github.com/microsoft/playwright-dotnet/issues/2941

chore: dispose APIRequestContext on BrowserContext close

---

README.md
src/Common/Version.props
src/Playwright.Tests/PageEvaluateTests.cs
src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs

https://github.com/microsoft/playwright-dotnet/issues/2969

chore: align with upstream exception handling

---

src/Playwright.Tests/ClientCertficatesTests.cs
src/Playwright.Tests/PageRouteTests.cs
src/Playwright/Core/BrowserType.cs

drive-by: address two other TODO comments.

chore: remap persistent-context options into context options

---

src/Playwright/Playwright.csproj

The `DedupeDriver` target doesn't exist anywhere so the `EnsurePrerequisitsRan` never runs. If the drivers were never downloaded by `Playwright.Tooling` then the following occurs when building `Playwright.csproj` if `EnsurePrerequisitsRan` doesn't run before:
```
Playwright failed with 5 error(s) (3.0s)
/usr/local/share/dotnet/sdk/8.0.401/Microsoft.Common.CurrentVersion.targets(5321,5): error MSB3030: Could not copy the file "~/playwright-dotnet/src/Playwright/.drivers/linux/node" because it was not found.
/usr/local/share/dotnet/sdk/8.0.401/Microsoft.Common.CurrentVersion.targets(5321,5): error MSB3030: Could not copy the file "~/playwright-dotnet/src/Playwright/.drivers/mac-arm64/node" because it was not found.
/usr/local/share/dotnet/sdk/8.0.401/Microsoft.Common.CurrentVersion.targets(5 …
```

Actually run the `EnsurePrerequisitsRan` target

---

README.md
src/Common/Version.props
src/Playwright.Tests/BrowserContextFetchTests.cs
src/Playwright.Tests/ClientCertficatesTests.cs
src/Playwright/API/Generated/IAPIResponse.cs
src/Playwright/API/Generated/IBrowserContext.cs
src/Playwright/API/Generated/IPageAssertions.cs
src/Playwright/API/Generated/IRoute.cs
src/Playwright/API/Generated/Options/APIRequestContextOptions.cs
src/Playwright/API/Generated/Options/APIRequestNewContextOptions.cs
src/Playwright/API/Generated/Options/BrowserNewContextOptions.cs
src/Playwright/API/Generated/Options/BrowserNewPageOptions.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchPersistentContextOptions.cs
src/Playwright/API/Generated/Options/ElementHandleSelectOptionOptions.cs
src/Playwright/API/Generated/Options/FrameSelectOptionOptions.cs
src/Playwright/API/Generated/Options/LocatorSelectOptionOptions.cs
src/Playwright/API/Generated/Options/PageRouteFromHAROptions.cs
src/Playwright/API/Generated/Options/PageSelectOptionOptions.cs
src/Playwright/API/Generated/Types/ClientCertificate.cs
src/Playwright/Core/APIRequestContext.cs
src/Playwright/Core/Browser.cs
src/Playwright/Core/ElementHandle.cs
src/Playwright/Core/Frame.cs
src/Playwright/Transport/Protocol/Generated/PlaywrightInitializer.cs

Fixes https://github.com/microsoft/playwright-dotnet/issues/2969

chore(roll): roll Playwright to v1.47.0

---

src/Playwright.MSTest/Playwright.MSTest.csproj
src/Playwright.NUnit/Playwright.NUnit.csproj

17.8 is the minimum which gets suggested when you create a new mstest/nunit project via the CLI in net8.0. This bumps Newtonsoft.Json to `13.0.1` which is not vulnerable.
Fixes https://github.com/microsoft/playwright-dotnet/issues/3050

chore: set Microsoft.NET.Test.Sdk minimum to 17.8.0

---

ROLLING.md
build.sh

`--update-assets` was unused and `--init` is the same as `--download-driver`.

chore: clean up build.sh script

---

src/Playwright.NUnit/WorkerAwareTest.cs

This warning regressed in https://github.com/microsoft/playwright-dotnet/pull/3042. It was [non-nullable](https://github.com/microsoft/playwright-dotnet/pull/3042/files#diff-e98b51acc76a0cbe47e1e8f7eaaadac017efa17a01ea3dc1016cbe9dc8440117) before so it should be fine to restore that.

chore: fix 'Dereference of a possibly null reference.' warning

---

src/Playwright.CLI/Playwright.CLI.csproj

We don't plant to release a new version anymore but this produced the following warning:
```
/usr/local/share/dotnet/sdk/9.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(32,5): warning NETSDK1138: The target framework 'net7.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
```

chore: drop net6.0/net7.0 from Playwright.CLI

---

.azure-pipelines/publish.yml

- Updates Microbuild plugin: We received a warning that it was using Node.js 10 under the hood
- Semicolon separate instead, to workaround [this](https://portal.microsofticm.com/imp/v3/incidents/details/467483180/home)

devops: AzDO publishing fixes

---

src/Playwright.Xunit/BrowserTest.cs
src/Playwright.Xunit/Playwright.Xunit.csproj
src/Playwright.Xunit/WorkerAwareTest.cs

`ModuleInitializer` was something which was not supported in older .NET frameworks. This patch starts listening on the constructor instead and resets the TestOK status in TestInitialize.
Background: xUnit 2 does not provide a reliable way of determining if a test was passing or failing and reading it's status in the AfterEach. xUnit 3 allows to read its status which we'll use once its published. We want to support xUnit 2 as well.
https://github.com/microsoft/playwright-dotnet/issues/2977

fix(xunit): support netstandard2.0

---

.azure-pipelines/publish.yml

Migrate to MicroBuild templates which does Microbuild setup under the hood and fixes Guardian compliance issues.

devops: migrate to MicroBuildTemplates

---

.azure-pipelines/publish.yml

https://github.com/microsoft/playwright-dotnet/issues/2977

chore: start publishing Microsoft.Playwright.Xunit

---

src/Playwright.Xunit/Playwright.Xunit.csproj

See [xUnit.net documentation - What NuGet Packages Should I Use?][1]
[1]: https://xunit.net/docs/nuget-packages

Depend on xunit.extensibility.core instead of xunit

---

src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs

e.g. `/vscode/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/helpers/browser.sh` which prevents customers from running the getting started on GitHub Codespaces.
We respect the `BROWSER` env var for legacy reasons.
Fixes https://github.com/microsoft/playwright-dotnet/issues/2847

chore: ignore GitHub Codespaces BROWSER env var

---

src/Playwright.Tests/PageRouteWebSocketTests.cs
src/Playwright/Core/PageAssertions.cs
src/Playwright/Helpers/URLMatch.cs

Might affect Java as well.
Relates https://github.com/microsoft/playwright-python/issues/2686.

fix(webSocketRoute): support no trailing slash

---

src/Playwright.TestingHarnessTest/Playwright.TestingHarnessTest.csproj
src/Playwright.TestingHarnessTest/tests/baseTest.ts
src/Playwright.TestingHarnessTest/tests/mstest/basic.spec.ts
src/Playwright.TestingHarnessTest/tests/nunit/basic.spec.ts
src/Playwright.TestingHarnessTest/tests/xunit/basic.spec.ts

This has two benefits:
a) that the test-projects don't have other test frameworks loaded
b) helps us to fix namespace clashes between test frameworks (esp. xunit2 vs xunit3)
= 4.6min -> 3.6min

test: isolate test-projects from each-other

---

src/Playwright/build/Microsoft.Playwright.targets

This aligns the items with the built-in mechanism in nuget for providing content items, and enables reliable detection of these items in consuming projects.
Fixes #3108

When adding content items via targets, provide the NuGetPackageId metadata

---

build.sh
src/Playwright.TestingHarnessTest/package-lock.json
src/Playwright.TestingHarnessTest/package.json

This is needed since https://github.com/microsoft/playwright-dotnet/pull/3098.

chore: update testing harness pw version when rolling

---

src/Playwright.Tests/Attributes/PlaywrightTestAttribute.cs
src/Playwright.Tests/BrowserContextBasicTests.cs
src/Playwright.Tests/ElementHandleConvenienceTests.cs
src/Playwright.Tests/PageDispatchEventTests.cs
src/Playwright.Tests/PageEvaluateTests.cs
src/Playwright.Tests/PageNetworkRequestTest.cs
src/Playwright.Tests/PageWaitForNavigationTests.cs
src/Playwright.Tests/ScreencastTests.cs
src/Playwright.Tests/TestConstants.cs

This only affects our internal tests.
Fixes https://github.com/microsoft/playwright-dotnet/issues/3118

chore: migrate from TimeoutAttribute to CancelAfterAttribute

---

src/Common/Dependencies.props

This should fix:
```
C:\Users\runneradmin\.nuget\packages\microsoft.codeanalysis.netanalyzers\8.0.0\buildTransitive\Microsoft.CodeAnalysis.NetAnalyzers.targets(648,5): warning : The .NET SDK has newer analyzers with version '9.0.0' than what version '8.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. You can suppress this warning by setting the MSBuild property '_SkipUpgradeNetAnalyzersNuGetWarning' to 'true'. [D:\a\playwright-dotnet\playwright-dotnet\src\Playwright\Playwright.csproj]
1 Warning(s)
0 Error(s)
```
locally and on CI. These packages are primarily used for linting.

chore: bump analyser packages

---

src/Playwright.Tests/Attributes/PlaywrightTestAttribute.cs
src/Playwright.Tests/BaseTests/HttpService.cs
src/Playwright.Tests/BrowserTypeConnectTests.cs
src/Playwright.Tests/ClientCertficatesTests.cs
src/Playwright.Tests/PageSetInputFilesTests.cs
src/Playwright.Tests/PageWaitForNavigationTests.cs
src/Playwright.Tests/Playwright.Tests.csproj

What does it fix?
- When a test was infinitely hanging the test-runner was infinitely waiting as well and the test was not aborted. This ended up in a timeout on GHA.
- When a test was ending in a timeout we didn't retry it on CI. Ideally we retry timeouts. This was caused by the order of Commands, our custom RetryCommand was before the nunit TimeoutCommand.
Notes:
- CancelAfterAttribute [just cancels the CancellationToken](https://docs.nunit.org/articles/nunit/writing-tests/attributes/cancelafter.html) of a test, this is not what we want.
- TimeoutAttribute is [considered deprecated](https://github.com/nunit/nunit/blob/main/src/NUnitFramework/framework/Attributes/TimeoutAttribute.cs) because it does not cancel the thread anymore, it does just instead cancel the task (not underlying) and …

chore: use manual TimeoutAttribute instead of CancelAfter attribute

---

src/Playwright/Transport/Connection.cs

Looks like this was changed [here](https://github.com/microsoft/playwright/commit/2a3d67195dff6ece12bd36aab970a1fc95776998#diff-b6f15e1e595e78791af29171502861070168d93fac02cdd83fd8d99d535e9540L137). Fixes https://github.com/microsoft/playwright-dotnet/issues/3132
Before:
```
➜  Playwright.Examples git:(fix-calllog-formatting) ✗ dotnet run Program.cs
Unhandled exception. System.TimeoutException: Timeout 1000ms exceeded.
Call log:
-   - waiting for Locator("textarea")
-     - locator resolved to <textarea disabled></textarea>
-     - fill("12")
-   - attempting fill action
-     2 × waiting for element to be visible, enabled and editable
-       - element is not enabled
-     - retrying fill action
-     - waiting 20ms
-     2 × waiting for element to be visible, enabled and editable
- …
```

fix: CallLog formatting

---

README.md
src/Common/Version.props
src/Playwright.TestingHarnessTest/package-lock.json
src/Playwright.TestingHarnessTest/package.json
src/Playwright.Tests/Assertions/LocatorAssertionsTests.cs
src/Playwright.Tests/GlobalFetchTests.cs
src/Playwright.Tests/PageAriaSnapshotTests.cs
src/Playwright.Tests/PageClockTests.cs
src/Playwright.Tests/PageEvaluateTests.cs
src/Playwright.Tests/PageRouteTests.cs
src/Playwright/API/Generated/IBrowserContext.cs
src/Playwright/API/Generated/IBrowserType.cs
src/Playwright/API/Generated/ILocatorAssertions.cs
src/Playwright/API/Generated/IPage.cs
src/Playwright/API/Generated/IRoute.cs
src/Playwright/API/Generated/Options/APIRequestNewContextOptions.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchOptions.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchPersistentContextOptions.cs
src/Playwright/API/Generated/Options/LocatorAriaSnapshotOptions.cs
src/Playwright/API/Generated/Options/LocatorAssertionsToContainClassOptions.cs
src/Playwright/API/Generated/Options/LocatorEvaluateHandleOptions.cs
src/Playwright/API/Generated/Options/LocatorEvaluateOptions.cs
src/Playwright/Core/APIRequest.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/Locator.cs
src/Playwright/Core/LocatorAssertions.cs
src/Playwright/Transport/Converters/EvaluateArgumentValueConverter.cs
src/Playwright/Transport/Protocol/Generated/SerializedValueTa.cs

This does not switch to `LocalUtils.globToRegex` yet.

chore: roll to 1.53.0-alpha-1744741041000

---

src/Playwright.Tests/InterceptionTests.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/Page.cs
src/Playwright/Helpers/StringExtensions.cs
src/Playwright/Helpers/URLMatch.cs

Implements https://github.com/microsoft/playwright/pull/35136 and https://github.com/microsoft/playwright/pull/34923.

chore: update URLMatch to follow upstream

---

src/Playwright.Tests/BrowserContextCookiesTests.cs
src/Playwright/Core/BrowserContext.cs

We used to accept `null` before https://github.com/microsoft/playwright-dotnet/pull/3145 - this was also aligned with which types we accepted. A `string` can be null or a `string[]` can be null. This PR adds back the null checks / falls back to an empty array so it doesn't crash.
https://github.com/microsoft/playwright-dotnet/issues/3161

fix: CookiesAsync regression accepting null

---

README.md
src/Common/Version.props
src/Playwright.TestingHarnessTest/package-lock.json
src/Playwright.TestingHarnessTest/package.json
src/Playwright.Tests/BrowserContextCookiesTests.cs
src/Playwright.Tests/PageAriaSnapshotTests.cs
src/Playwright.Tests/TracingTests.cs
src/Playwright/API/Generated/ILocator.cs
src/Playwright/API/Generated/ILocatorAssertions.cs
src/Playwright/API/Generated/ITracing.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchOptions.cs
src/Playwright/API/Generated/Options/BrowserTypeLaunchPersistentContextOptions.cs
src/Playwright/API/Generated/Options/LocatorAriaSnapshotOptions.cs
src/Playwright/Core/APIRequest.cs
src/Playwright/Core/APIRequestContext.cs
src/Playwright/Core/BrowserContext.cs
src/Playwright/Core/BrowserType.cs
src/Playwright/Core/ElementHandle.cs
src/Playwright/Core/Frame.cs
src/Playwright/Core/Locator.cs
src/Playwright/Core/Page.cs
src/Playwright/Core/TimeoutSettings.cs

Covers https://github.com/microsoft/playwright/pull/35888, https://github.com/microsoft/playwright/pull/35969 and https://github.com/microsoft/playwright/pull/35988.
References #3149.

chore: roll driver to 1.53.0-alpha-2025-05-21

---

src/Playwright.Tests/TracingTests.cs

This gives us more confidence in the Trace Viewer tests and should in the future allow us to port more tests over to .NET.

test: refactor TracingTests to use actual Trace Viewer

---

src/Playwright.MSTest/WorkerAwareTest.cs

`WorkerAwareTest` is designed to be inherited for testing. As such, the TestContext property, which is injected by the test framework, should be marked `virtual` so that inheritors can override behavior as necessary.
Fixes #3209.

feat(mstest): Mark TestContext as virtual

---

src/Common/Version.props

The last build was only published half because the API key only had permissions to publish to existing packages, not create new ones.

chore: mark v1.55.0-beta-3
